export const LX_API_NAMES = [
  'app',
  'automation',
  'chooseDirectory',
  'chooseFile',
  'chooseMedia',
  'compressImage',
  'compressVideo',
  'connectWifi',
  'createVideoContext',
  'downloadFile',
  'env',
  'extractVideoThumbnail',
  'getCapsuleRect',
  'getConnectedWifi',
  'getDeviceInfo',
  'getFileManager',
  'getImageInfo',
  'getLocation',
  'getLxAppInfo',
  'getNetworkInfo',
  'getScreenInfo',
  'getStorage',
  'getSystemSetting',
  'getUpdateManager',
  'getVideoInfo',
  'getWifiList',
  'hideHomeButton',
  'hideTabBar',
  'hideTabBarRedDot',
  'hideToast',
  'makePhoneCall',
  'navigateBack',
  'navigateBackLxApp',
  'navigateTo',
  'navigateToLxApp',
  'offDeviceOrientationChange',
  'offKeyDown',
  'offKeyUp',
  'offNetworkChange',
  'offWifiConnected',
  'onDeviceOrientationChange',
  'onKeyDown',
  'onKeyUp',
  'onNetworkChange',
  'onSurfaceContext',
  'onWifiConnected',
  'openExternal',
  'openFile',
  'openSurface',
  'previewMedia',
  'reLaunch',
  'redirectTo',
  'removeTabBarBadge',
  'saveImageToPhotosAlbum',
  'saveVideoToPhotosAlbum',
  'scanCode',
  'setDeviceOrientation',
  'setNavigationBarColor',
  'setNavigationBarTitle',
  'setTabBarBadge',
  'setTabBarItem',
  'setTabBarStyle',
  'share',
  'shell',
  'showActionSheet',
  'showModal',
  'showTabBar',
  'showTabBarRedDot',
  'showToast',
  'startPullDownRefresh',
  'startWifi',
  'stopPullDownRefresh',
  'stopWifi',
  'switchTab',
  'tray',
  'uploadFile',
  'vibrateLong',
  'vibrateShort',
] as const;
const HOST_APP_API = [
  'autostart',
  'checkUpdate',
  'envVersion',
  'exit',
  'getBaseInfo',
  'screenshot',
  'setBadge',
] as const;
const AUTOSTART_API = ['isEnabled', 'setEnabled'] as const;
const ENV_API = ['USER_CACHE_PATH', 'USER_DATA_PATH'] as const;
const SHELL_API = ['activators'] as const;
const SHELL_ACTIVATORS_API = ['clear', 'remove', 'replace', 'update'] as const;
const TRAY_API = ['hide', 'onClick', 'setBadge', 'setIcon', 'setMenu', 'setTitle', 'show'] as const;
const FILE_MANAGER_API = [
  'copyFile',
  'exists',
  'mkdir',
  'readDir',
  'readFile',
  'remove',
  'rename',
  'stat',
  'writeFile',
] as const;
const STORAGE_API = ['clear', 'delete', 'get', 'info', 'list', 'set'] as const;
const UPDATE_MANAGER_API = ['applyUpdate', 'onUpdateFailed', 'onUpdateReady'] as const;
const VIDEO_CONTEXT_API = [
  'exitFullScreen',
  'pause',
  'play',
  'requestFullScreen',
  'seek',
  'setStreamSource',
  'stop',
] as const;

const AUTOMATION_API = ['browser', 'desktop', 'device', 'lxapp', 'lxapps'] as const;
const LXAPP_DRIVER_API = ['eval', 'info', 'nav', 'page', 'pages'] as const;
const LXAPP_MANAGER_API = [
  'close',
  'current',
  'list',
  'open',
  'restart',
  'screenshot',
  'uninstall',
  'windows',
] as const;
const PAGE_DRIVER_API = [
  'click',
  'eval',
  'fill',
  'key',
  'pointer',
  'press',
  'query',
  'screenshot',
  'scroll',
  'scrollTo',
  'type',
  'waitFor',
] as const;
const PAGE_POINTER_API = ['click', 'down', 'drag', 'move', 'scroll', 'up'] as const;
const PAGE_KEY_API = ['press', 'type'] as const;
const NAV_DRIVER_API = [
  'back',
  'current',
  'info',
  'redirect',
  'relaunch',
  'stack',
  'switchTab',
  'to',
] as const;
const DEVICE_DRIVER_API = ['get', 'list', 'set'] as const;
const BROWSER_DRIVER_API = [
  'activate',
  'back',
  'click',
  'close',
  'cookies',
  'current',
  'eval',
  'fill',
  'forward',
  'open',
  'press',
  'query',
  'reload',
  'screenshot',
  'scroll',
  'scrollTo',
  'tabs',
  'type',
  'wait',
] as const;
const BROWSER_COOKIES_API = ['clear', 'delete', 'list', 'set'] as const;
const DESKTOP_DRIVER_API = [
  'app',
  'ax',
  'clipboard',
  'displays',
  'doctor',
  'key',
  'permissions',
  'pixel',
  'pointer',
  'process',
  'screenshot',
  'snapshot',
  'wait',
  'window',
  'windows',
] as const;
const DESKTOP_POINTER_API = ['click', 'down', 'drag', 'move', 'scroll', 'up'] as const;
const DESKTOP_KEY_API = ['down', 'press', 'type', 'up'] as const;
const DESKTOP_WINDOW_API = [
  'activate',
  'close',
  'focus',
  'maximize',
  'minimize',
  'moveTo',
  'moveToDisplay',
  'raise',
  'resize',
  'restore',
  'setAlwaysOnTop',
  'status',
] as const;
const DESKTOP_CLIPBOARD_API = ['clear', 'get', 'paste', 'set'] as const;
const DESKTOP_AX_API = [
  'collapse',
  'expand',
  'focus',
  'hitTest',
  'invoke',
  'query',
  'scrollIntoView',
  'select',
  'setValue',
  'tree',
] as const;
const DESKTOP_WAIT_API = ['ax', 'pixel', 'window'] as const;
const DESKTOP_APP_API = ['launch', 'quit'] as const;
const DESKTOP_PROCESS_API = ['kill', 'list'] as const;

export const LX_RUNTIME_SURFACES = [
  { name: 'lx', expression: 'lx', members: LX_API_NAMES },
  { name: 'lx.app', expression: 'lx.app', members: HOST_APP_API },
  { name: 'lx.app.autostart', expression: 'lx.app.autostart', members: AUTOSTART_API },
  { name: 'lx.env', expression: 'lx.env', members: ENV_API },
  { name: 'lx.shell', expression: 'lx.shell', members: SHELL_API },
  { name: 'lx.shell.activators', expression: 'lx.shell.activators', members: SHELL_ACTIVATORS_API },
  { name: 'lx.tray', expression: 'lx.tray', members: TRAY_API },
  { name: 'FileManager', expression: 'lx.getFileManager()', members: FILE_MANAGER_API },
  { name: 'Storage', expression: 'lx.getStorage()', members: STORAGE_API },
  { name: 'UpdateManager', expression: 'lx.getUpdateManager()', members: UPDATE_MANAGER_API },
  { name: 'Automation', expression: 'lx.automation()', members: AUTOMATION_API },
  { name: 'LxAppDriver', expression: 'lx.automation().lxapp()', members: LXAPP_DRIVER_API },
  { name: 'PageDriver', expression: 'lx.automation().lxapp().page', members: PAGE_DRIVER_API },
  { name: 'PagePointer', expression: 'lx.automation().lxapp().page.pointer', members: PAGE_POINTER_API },
  { name: 'PageKey', expression: 'lx.automation().lxapp().page.key', members: PAGE_KEY_API },
  { name: 'NavDriver', expression: 'lx.automation().lxapp().nav', members: NAV_DRIVER_API },
  { name: 'LxAppManager', expression: 'lx.automation().lxapps', members: LXAPP_MANAGER_API },
  { name: 'DeviceDriver', expression: 'lx.automation().device', members: DEVICE_DRIVER_API },
  { name: 'BrowserDriver', expression: 'lx.automation().browser', members: BROWSER_DRIVER_API },
  { name: 'BrowserCookies', expression: 'lx.automation().browser.cookies', members: BROWSER_COOKIES_API },
  { name: 'DesktopDriver', expression: 'lx.automation().desktop', members: DESKTOP_DRIVER_API },
  { name: 'DesktopPointer', expression: 'lx.automation().desktop.pointer', members: DESKTOP_POINTER_API },
  { name: 'DesktopKey', expression: 'lx.automation().desktop.key', members: DESKTOP_KEY_API },
  { name: 'DesktopWindow', expression: 'lx.automation().desktop.window', members: DESKTOP_WINDOW_API },
  { name: 'DesktopClipboard', expression: 'lx.automation().desktop.clipboard', members: DESKTOP_CLIPBOARD_API },
  { name: 'DesktopAx', expression: 'lx.automation().desktop.ax', members: DESKTOP_AX_API },
  { name: 'DesktopWait', expression: 'lx.automation().desktop.wait', members: DESKTOP_WAIT_API },
  { name: 'DesktopApp', expression: 'lx.automation().desktop.app', members: DESKTOP_APP_API },
  { name: 'DesktopProcess', expression: 'lx.automation().desktop.process', members: DESKTOP_PROCESS_API },
] as const;

const DOWNLOAD_TASK_API = [
  'abort',
  'cancel',
  'catch',
  'finally',
  'next',
  'pause',
  'resume',
  'return',
  'then',
  'wait',
] as const;
const UPLOAD_TASK_API = ['cancel', 'catch', 'finally', 'next', 'return', 'then', 'wait'] as const;
const COMPRESS_VIDEO_TASK_API = ['cancel', 'catch', 'finally', 'next', 'return', 'then', 'wait'] as const;
const HOST_UPDATE_INFO_API = ['apply', 'isForceUpdate', 'releaseNotes', 'size', 'version'] as const;
const HOST_UPDATE_TASK_API = ['catch', 'finally', 'next', 'return', 'then', 'wait'] as const;
const PREVIEW_MEDIA_API = ['completed', 'current', 'onChange', 'presented'] as const;
const SURFACE_HANDLE_API = [
  'alive',
  'close',
  'hide',
  'id',
  'onClose',
  'onHide',
  'onShow',
  'presentation',
  'role',
  'show',
  'visible',
] as const;
const SURFACE_API = [
  'alive',
  'close',
  'hide',
  'id',
  'kind',
  'onClose',
  'onHide',
  'onMessage',
  'onShow',
  'postMessage',
  'presentation',
  'role',
  'show',
  'visible',
] as const;
const PAGE_MESSAGE_PORT_API = ['onMessage', 'postMessage'] as const;
