export {
  LX_API_NAMES,
  LX_REQUIRED_RUNTIME_SHAPE_NAMES,
  LX_RETURNED_OBJECT_CAPABILITY_NAMES,
  LX_RETURNED_OBJECT_SHAPE_NAMES,
  LX_RETURNED_OBJECT_SURFACES,
  LX_RUNTIME_CAPABILITY_NAMES,
  LX_RUNTIME_SHAPE_NAMES,
  LX_RUNTIME_SURFACES,
} from 'lingxia-types/testing';
