// Auto-generated by lingxia-cli. Do not edit.
export function __lx_filter_payload(name, args) {
  const clean = [];
  for (let i = 0; i < args.length; i += 1) {
    const value = args[i];
    // CustomEvent carries serializable data on `.detail`. Repackage as a plain
    // `{type, detail}` so page actions bound directly to DOM events (e.g.
    // `onVideoEnded={action}`) keep the familiar `event.detail` shape without
    // forwarding the non-portable Event instance. Stripping it wholesale —
    // which is what the previous unconditional `instanceof Event` did — is
    // why every event-driven page action received `undefined` and the showcase
    // logged "video ended undefined".
    if (typeof CustomEvent !== "undefined" && value instanceof CustomEvent) {
      clean.push({ type: value.type, detail: value.detail });
      continue;
    }
    // Cross-realm safety: in some WebView setups (Harmony/iOS WKWebView under
    // certain configurations) the CustomEvent flowing through the React/Vue
    // wrapper does NOT satisfy `instanceof CustomEvent` from the page-runtime
    // realm, because the CustomEvent constructor reference differs across
    // frames or contexts. Duck-type the same `{type: string, detail}` shape
    // before the generic Event stripping path so these wrapped events still
    // forward their payload instead of getting eaten by the stopPropagation
    // guard below.
    if (
      value
      && typeof value === "object"
      && typeof value.type === "string"
      && "detail" in value
    ) {
      clean.push({ type: value.type, detail: value.detail });
      continue;
    }
    if (value instanceof Event) continue;
    if (value && typeof value === "object" && typeof value.stopPropagation === "function") continue;
    clean.push(value);
  }
  if (clean.length > 1) {
    throw new Error(`Page action '${name}' accepts at most one payload argument`);
  }
  return clean.length === 0 ? undefined : clean[0];
}

export function __lx_define_page_bridge(name, mode) {
  function fn(...args) {
    const payload = __lx_filter_payload(name, args);
    const bridge = window.LingXiaBridge;
    if (!bridge || !bridge.raw) {
      throw new Error(`LingXiaBridge is not ready for page action '${name}'`);
    }
    if (mode === 'stream') {
      const handle = bridge.raw.stream(name, payload);
      if (handle && handle.result && typeof handle.result.catch === 'function') {
        handle.result.catch((err) => {
          console.warn(`[PageFunc] ${name} failed:`, err && err.message ? err.message : err);
        });
      }
      return handle;
    }
    if (mode === 'call') {
      const promise = bridge.raw.call(name, payload);
      if (promise && typeof promise.catch === 'function') {
        promise.catch((err) => {
          console.warn(`[PageFunc] ${name} failed:`, err && err.message ? err.message : err);
        });
      }
      return promise;
    }
    bridge.raw.notify(name, payload);
  }
  fn.__logicFunc = true;
  fn.__funcName = name;
  fn.__bridgeMode = mode;
  return fn;
}
