//! The shim that makes the product's command typable.
//!
//! The real executable lives inside an application bundle, which is neither on
//! `PATH` nor pleasant to type. This writes a small script that points at it,
//! generated at runtime rather than at build time so it always names the
//! executable actually running — a development build moves, a release does not.
//!
//! It lives beside the socket rather than with the command line it launches,
//! because it has to carry the endpoint, and only this side knows one.

use std::path::{Path, PathBuf};

use lingxia_devtool_protocol::invocation;

/// Directory holding the launcher, added to `PATH` for sessions we spawn.
pub fn bin_dir(state_dir: &Path) -> PathBuf {
    state_dir.join("bin")
}

/// Write the launcher, returning where it landed.
pub fn install(state_dir: &Path, endpoint: &str) -> std::io::Result<PathBuf> {
    let executable = std::env::current_exe()?;
    let name = command_name(&executable_stem(&executable));
    let directory = bin_dir(state_dir);
    std::fs::create_dir_all(&directory)?;
    let (file_name, script) = script(&name, &executable, endpoint);
    let path = directory.join(file_name);
    if std::fs::read_to_string(&path).unwrap_or_default() != script {
        std::fs::write(&path, &script)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
        }
    }
    Ok(path)
}

/// The other half of a switch that can be turned off. One that only ever adds
/// leaves the machine littered.
pub fn remove(state_dir: &Path) -> std::io::Result<()> {
    let executable = std::env::current_exe()?;
    let name = command_name(&executable_stem(&executable));
    let (file_name, _) = script(&name, &executable, "");
    match std::fs::remove_file(bin_dir(state_dir).join(file_name)) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        other => other,
    }
}

/// Lowercased and stripped to what a shell takes without quoting: the name
/// exists to be typed, and a product called "My App" must not require escaping.
pub fn command_name(product_name: &str) -> String {
    let mut name = String::new();
    for character in product_name.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else if !name.is_empty() && !name.ends_with('-') {
            name.push('-');
        }
    }
    let name = name.trim_end_matches('-');
    if name.is_empty() {
        "app".to_string()
    } else {
        name.to_string()
    }
}

/// The executable's name without whatever suffix this platform puts on one.
///
/// `EXE_SUFFIX` is empty off Windows, so this is one expression rather than a
/// `cfg` — the same reason `join_paths` above replaces a `:` and a `;`.
fn executable_stem(executable: &Path) -> String {
    let name = executable
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("app");
    name.strip_suffix(std::env::consts::EXE_SUFFIX)
        .unwrap_or(name)
        .to_string()
}

/// A shell script and a `.cmd` shim are genuinely different artifacts, so this
/// is the one place that forks.
#[cfg(not(windows))]
fn script(name: &str, executable: &Path, endpoint: &str) -> (String, String) {
    // `exec -a` so the program sees the name that was typed: help text quotes
    // argv[0], and every line of it has to be runnable as printed.
    let script = format!(
        "#!/bin/sh\n# Generated by LingXia; points at the running executable.\n{}=1 {}={} exec -a {} {} \"$@\"\n",
        invocation::MARKER,
        invocation::ENDPOINT,
        shell_quote(endpoint),
        shell_quote(name),
        shell_quote(&executable.to_string_lossy())
    );
    (name.to_string(), script)
}

/// `.cmd` is what `PATHEXT` makes typable as a bare name. It cannot rewrite
/// argv[0] the way `exec -a` does, and does not need to: the command name is
/// derived from the executable, which the shim leaves alone.
#[cfg(windows)]
fn script(name: &str, executable: &Path, endpoint: &str) -> (String, String) {
    let script = format!(
        "@echo off\r\nrem Generated by LingXia; points at the running executable.\r\nset {}=1\r\nset {}={endpoint}\r\n\"{}\" %*\r\n",
        invocation::MARKER,
        invocation::ENDPOINT,
        executable.display()
    );
    (format!("{name}.cmd"), script)
}

#[cfg(not(windows))]
fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn command_names_are_typable_without_quoting() {
        assert_eq!(command_name("LingXia Demo"), "lingxia-demo");
        assert_eq!(command_name("My  Term!!"), "my-term");
        assert_eq!(command_name("!!!"), "app");
    }

    #[test]
    fn the_script_names_the_executable_the_marker_and_the_endpoint() {
        let (file_name, body) = script(
            "foo",
            Path::new("/Apps/Foo.app/MacOS/Foo"),
            "/tmp/control.sock",
        );
        assert!(file_name.starts_with("foo"));
        assert!(body.contains("/Apps/Foo.app/MacOS/Foo"));
        assert!(body.contains(invocation::MARKER));
        assert!(
            body.contains("/tmp/control.sock"),
            "a Windows client has no other way to learn the pipe's name"
        );
    }

    #[test]
    fn installing_is_idempotent_and_removing_is_forgiving() {
        let state_dir =
            std::env::temp_dir().join(format!("lingxia-launcher-{}", std::process::id()));
        std::fs::create_dir_all(&state_dir).unwrap();
        let first = install(&state_dir, "/tmp/control.sock").unwrap();
        let second = install(&state_dir, "/tmp/control.sock").unwrap();
        assert_eq!(first, second);
        assert!(first.exists());
        remove(&state_dir).unwrap();
        assert!(!first.exists());
        // Removing what is already gone is what a toggle flipped twice does.
        remove(&state_dir).unwrap();
        let _ = std::fs::remove_dir_all(&state_dir);
    }
}
