use std::{
    fs,
    path::{Path, PathBuf},
};

pub fn configure_windows_app() {
    configure_windows_app_with_manifest("app.manifest");
}

pub fn configure_windows_app_with_manifest(manifest: impl AsRef<Path>) {
    if !is_windows_target() {
        return;
    }

    let manifest = manifest.as_ref();
    let manifest_path = resolve_manifest_path(manifest);

    // The resource compiler owns the manifest (never also pass `/MANIFEST`
    // linker args: two manifests collide) so the version resource is embedded
    // whether or not the project ships an `AppIcon.ico`.
    embed_resources(&manifest_path, prepared_app_icon().as_deref());
    emit_gui_subsystem_args();
    println!("cargo:rerun-if-changed={}", manifest.display());
    configure_local_debug_assets();
}

/// Like [`configure_windows_app`], with an explicit `.ico` so the binary shows
/// its icon in Explorer / taskbar / Alt-Tab *before any code runs* (the dev
/// runner ships as a loose exe; a packaged app ships in a zip).
pub fn configure_windows_app_with_icon(manifest: impl AsRef<Path>, icon: impl AsRef<Path>) {
    if !is_windows_target() {
        return;
    }

    let manifest_path = resolve_manifest_path(manifest.as_ref());
    let icon_path = resolve_manifest_path(icon.as_ref());
    embed_resources(&manifest_path, Some(&icon_path));
    emit_gui_subsystem_args();
    configure_local_debug_assets();
}

/// The committed `<crate>/AppIcon.ico`, generated by
/// `lingxia icon … --platform windows` (like every other platform's icon
/// resource). Embedded automatically when present.
fn prepared_app_icon() -> Option<PathBuf> {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR")?);
    let icon = manifest_dir.join("AppIcon.ico");
    icon.is_file().then_some(icon)
}

/// Compile the manifest, version info and optional `.ico` into the binary via
/// the resource compiler. winresource emits its own link directives.
fn embed_resources(manifest_path: &Path, icon_path: Option<&Path>) {
    let mut res = winresource::WindowsResource::new();
    if let Some(icon_path) = icon_path {
        res.set_icon(
            icon_path
                .to_str()
                .expect("Windows icon path is not valid UTF-8"),
        );
        println!("cargo:rerun-if-changed={}", icon_path.display());
    }
    res.set_manifest_file(
        manifest_path
            .to_str()
            .expect("Windows manifest path is not valid UTF-8"),
    );
    set_product_version_info(&mut res);
    res.compile()
        .expect("failed to compile Windows .exe resources (icon/manifest/version)");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
}

/// Explorer, Task Manager and taskbar pins read the exe's version resource;
/// without this it carries the generated crate's name and `0.1.0`.
fn set_product_version_info(res: &mut winresource::WindowsResource) {
    println!("cargo:rerun-if-env-changed=LINGXIA_PRODUCT_NAME");
    println!("cargo:rerun-if-env-changed=LINGXIA_PRODUCT_VERSION");
    if let Ok(name) = std::env::var("LINGXIA_PRODUCT_NAME") {
        res.set("ProductName", &name);
        res.set("FileDescription", &name);
    }
    let Ok(version) = std::env::var("LINGXIA_PRODUCT_VERSION") else {
        return;
    };
    res.set("ProductVersion", &version);
    res.set("FileVersion", &version);
    if let Some(packed) = pack_version(&version) {
        res.set_version_info(winresource::VersionInfo::PRODUCTVERSION, packed);
        res.set_version_info(winresource::VersionInfo::FILEVERSION, packed);
    }
}

/// `major.minor.patch` as the binary `VS_FIXEDFILEINFO` quad (build = 0).
fn pack_version(version: &str) -> Option<u64> {
    let core = version.split(['-', '+']).next()?;
    let mut parts = core.split('.').map(|part| part.parse::<u16>().ok());
    let (major, minor, patch) = (parts.next()??, parts.next()??, parts.next()??);
    Some((u64::from(major) << 48) | (u64::from(minor) << 32) | (u64::from(patch) << 16))
}

fn emit_gui_subsystem_args() {
    println!("cargo:rustc-link-arg-bins=/SUBSYSTEM:WINDOWS");
    println!("cargo:rustc-link-arg-bins=/ENTRY:mainCRTStartup");
}

fn is_windows_target() -> bool {
    std::env::var("CARGO_CFG_TARGET_OS").ok().as_deref() == Some("windows")
        || std::env::var_os("CARGO_CFG_WINDOWS").is_some()
}

fn resolve_manifest_path(manifest: &Path) -> PathBuf {
    if manifest.is_absolute() {
        return manifest.to_path_buf();
    }
    std::env::current_dir()
        .expect("build script current directory")
        .join(manifest)
}

fn configure_local_debug_assets() {
    let Some(manifest_dir) = std::env::var_os("CARGO_MANIFEST_DIR").map(PathBuf::from) else {
        return;
    };
    println!("cargo:rerun-if-env-changed=LINGXIA_WINDOWS_ASSET_DIR");
    let source = std::env::var_os("LINGXIA_WINDOWS_ASSET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join(".lingxia").join("assets"));
    if !source.is_dir() {
        return;
    }

    watch_dir(&source);

    // Debug builds are local developer artifacts. Compile the prepared asset
    // dir into the host entrypoint instead of copying a second tree under
    // `target/debug/assets`.
    if std::env::var("PROFILE").ok().as_deref() == Some("debug") {
        println!(
            "cargo:rustc-env=LINGXIA_WINDOWS_DEBUG_ASSET_DIR={}",
            source.display()
        );
    }
}

fn watch_dir(source: &Path) {
    println!("cargo:rerun-if-changed={}", source.display());
    let Ok(entries) = fs::read_dir(source) else {
        return;
    };
    for entry in entries.flatten() {
        let file_name = entry.file_name();
        if file_name == ".lingxia" {
            continue;
        }
        let source_path = entry.path();
        println!("cargo:rerun-if-changed={}", source_path.display());
        if entry.file_type().map(|ty| ty.is_dir()).unwrap_or(false) {
            watch_dir(&source_path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::pack_version;

    #[test]
    fn packs_semver_into_version_quad() {
        assert_eq!(pack_version("0.1.3"), Some(0x0000_0001_0003_0000));
        assert_eq!(pack_version("1.2.3-beta.1"), Some(0x0001_0002_0003_0000));
        assert_eq!(pack_version("70000.0.0"), None);
    }
}
