use std::{
    fs,
    path::{Path, PathBuf},
};

pub fn configure_windows_app() {
    configure_windows_app_with_manifest("app.manifest");
}

pub fn configure_windows_app_with_manifest(manifest: impl AsRef<Path>) {
    if !is_windows_target() {
        return;
    }

    let manifest = manifest.as_ref();
    let manifest_path = resolve_manifest_path(manifest);

    // When the CLI staged an `.exe` icon next to the prepared assets, embed it
    // (with the manifest) via the resource compiler; otherwise embed just the
    // manifest via linker args. winresource owns the manifest in the icon path,
    // so the two manifest mechanisms never both run (no double-manifest).
    match prepared_app_icon() {
        Some(icon_path) => embed_icon_and_manifest(&manifest_path, &icon_path),
        None => {
            println!("cargo:rustc-link-arg-bins=/MANIFEST:EMBED");
            println!(
                "cargo:rustc-link-arg-bins=/MANIFESTINPUT:{}",
                manifest_path.display()
            );
        }
    }

    emit_gui_subsystem_args();
    println!("cargo:rerun-if-changed={}", manifest.display());
    configure_local_debug_assets();
}

/// Like [`configure_windows_app`], but also compiles an `.exe` ICON resource so
/// the binary shows its icon in Explorer / taskbar / Alt-Tab *before any code
/// runs* (the dev runner ships as a loose exe; a packaged app ships in a zip).
///
/// Unlike [`configure_windows_app`], the manifest is embedded by the resource
/// compiler (`winresource`) alongside the icon and version info, so we must NOT
/// also inject `/MANIFEST` linker args — two manifests would collide.
pub fn configure_windows_app_with_icon(manifest: impl AsRef<Path>, icon: impl AsRef<Path>) {
    if !is_windows_target() {
        return;
    }

    let manifest_path = resolve_manifest_path(manifest.as_ref());
    let icon_path = resolve_manifest_path(icon.as_ref());
    embed_icon_and_manifest(&manifest_path, &icon_path);
    emit_gui_subsystem_args();
    configure_local_debug_assets();
}

/// The committed `<crate>/AppIcon.ico`, generated by
/// `lingxia icon … --platform windows` (like every other platform's icon
/// resource). Embedded automatically when present.
fn prepared_app_icon() -> Option<PathBuf> {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR")?);
    let icon = manifest_dir.join("AppIcon.ico");
    icon.is_file().then_some(icon)
}

/// Compile an `.ico` + manifest (+ version info) into the binary via the resource
/// compiler. winresource emits its own link directives and owns the manifest, so
/// callers must NOT also inject `/MANIFEST` args.
fn embed_icon_and_manifest(manifest_path: &Path, icon_path: &Path) {
    let mut res = winresource::WindowsResource::new();
    res.set_icon(
        icon_path
            .to_str()
            .expect("Windows icon path is not valid UTF-8"),
    );
    res.set_manifest_file(
        manifest_path
            .to_str()
            .expect("Windows manifest path is not valid UTF-8"),
    );
    res.compile()
        .expect("failed to compile Windows .exe resources (icon/manifest)");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", icon_path.display());
}

fn emit_gui_subsystem_args() {
    println!("cargo:rustc-link-arg-bins=/SUBSYSTEM:WINDOWS");
    println!("cargo:rustc-link-arg-bins=/ENTRY:mainCRTStartup");
}

fn is_windows_target() -> bool {
    std::env::var("CARGO_CFG_TARGET_OS").ok().as_deref() == Some("windows")
        || std::env::var_os("CARGO_CFG_WINDOWS").is_some()
}

fn resolve_manifest_path(manifest: &Path) -> PathBuf {
    if manifest.is_absolute() {
        return manifest.to_path_buf();
    }
    std::env::current_dir()
        .expect("build script current directory")
        .join(manifest)
}

fn configure_local_debug_assets() {
    let Some(manifest_dir) = std::env::var_os("CARGO_MANIFEST_DIR").map(PathBuf::from) else {
        return;
    };
    let source = manifest_dir.join(".lingxia").join("assets");
    if !source.is_dir() {
        return;
    }

    watch_dir(&source);

    // Debug builds are local developer artifacts. Keep the generated assets in
    // `windows/.lingxia/assets` and compile that path into the host entrypoint
    // instead of copying a second tree under `target/debug/assets`.
    if std::env::var("PROFILE").ok().as_deref() == Some("debug") {
        println!(
            "cargo:rustc-env=LINGXIA_WINDOWS_DEBUG_ASSET_DIR={}",
            source.display()
        );
    }
}

fn watch_dir(source: &Path) {
    println!("cargo:rerun-if-changed={}", source.display());
    let Ok(entries) = fs::read_dir(source) else {
        return;
    };
    for entry in entries.flatten() {
        let file_name = entry.file_name();
        if file_name == ".lingxia" {
            continue;
        }
        let source_path = entry.path();
        println!("cargo:rerun-if-changed={}", source_path.display());
        if entry.file_type().map(|ty| ty.is_dir()).unwrap_or(false) {
            watch_dir(&source_path);
        }
    }
}
