/** Pending backlog items that must or are worth automating, but are not at the
 *  tests/README bar yet. Bodies stay empty (`spec.skip`); modes stay off
 *  `automated` in logic-api-coverage.mjs. */
export default [
  {
    id: "PEND-TERMINAL-API-001",
    title: "Windows terminal integration runtime status, install, and setEnabled",
    mode: "external-fixture",
    covers: [
      "lx.terminal.windows.status",
      "lx.terminal.windows.install",
      "lx.terminal.windows.setEnabled",
    ],
    reason: "TERMINAL-API-001 covers the rest inside the bundled settings lxapp; the Windows-only integration needs a Windows run with an installable runtime",
  },
  {
    id: "PEND-DIRPICK-001",
    title: "chooseDirectory returns a grant the lxapp can read",
    mode: "external-ui",
    covers: ["lx.chooseDirectory"],
    reason: "the directory picker is an OS dialog with no in-process driver",
  },
  {
    id: "PEND-DESTRUCTIVE-001",
    title: "exit and applyUpdate end the host process under test",
    mode: "planned",
    covers: ["lx.app.exit", "UpdateManager.applyUpdate"],
    reason: "lx.app.exit exits the whole host (proven: calling it inside the bundled chat lxapp killed the dev session), so it needs an outer lane that owns the process, not an in-suite spec",
  },
  {
    id: "PEND-UPDATE-INFO-001",
    title: "HostAppUpdateInfo fields from a real staged host update",
    mode: "external-fixture",
    covers: ["HostAppUpdateInfo.isForceUpdate"],
    reason: "needs a cloud provider serving a staged host build to populate the info",
  },
  {
    id: "PEND-SHARE-001",
    title: "share text, page, and files through the OS share sheet",
    mode: "external-ui",
    covers: ["lx.share"],
    reason: "OS share sheet cannot be driven without a device-lab UI helper",
  },
  {
    id: "PEND-LOCATION-001",
    title: "getLocation through the Android / iOS permission sheet",
    mode: "external-ui",
    covers: ["lx.getLocation"],
    reason: "macOS is proven by MACOS-LOCATION-001 over AX; the mobile permission sheet still needs a device-lab UI driver",
  },
  {
    id: "PEND-MEDIA-PICK-001",
    title: "chooseMedia and scanCode pick a real file through the OS panel",
    mode: "external-ui",
    covers: ["lx.chooseMedia", "lx.scanCode"],
    reason: "the desktop file panel starves the in-process driver and hides its file rows from AX; previewMedia is DESKTOP-PREVIEW-MEDIA-001",
  },
  {
    id: "PEND-PHOTOS-001",
    title: "save into the photos album on iOS, where the permission sheet gates it",
    mode: "external-ui",
    covers: ["lx.saveImageToPhotosAlbum", "lx.saveVideoToPhotosAlbum"],
    reason: "Android is proven by ANDROID-PHOTOS-001 (MediaStore needs no prompt); iOS still shows the photos permission sheet",
  },
  {
    id: "PEND-ORIENT-001",
    title: "observe the host physically rotate after setDeviceOrientation",
    mode: "external-ui",
    covers: ["lx.setDeviceOrientation"],
    reason: "the return and argument contract is DEVICE-ORIENTATION-001; seeing the frame rotate is device-lab",
  },
  {
    id: "PEND-EXTERNAL-001",
    title: "openExternal launches the system browser",
    mode: "external-ui",
    covers: ["lx.openExternal"],
    reason: "system browser handoff cannot be asserted in-process",
  },
  {
    id: "PEND-DEVICE-FB-001",
    title: "vibrate and makePhoneCall on a phone",
    mode: "external-ui",
    covers: ["lx.vibrateShort", "lx.vibrateLong", "lx.makePhoneCall"],
    reason: "desktop is proven absent by DEVICE-ABSENT-001; the real haptics and dialer are device-lab",
  },
  {
    id: "PEND-MORE-ACTIONS-001",
    title: "setMoreActions overflow item opens the declared surface",
    mode: "external-ui",
    covers: ["lx.setMoreActions"],
    reason: "host chrome overflow menu is not exposed as a Logic contract yet",
  },
  {
    id: "PEND-FILE-PICK-001",
    title: "openFile and chooseFile cancel/error codes",
    mode: "external-ui",
    covers: ["lx.openFile", "lx.chooseFile"],
    reason: "OS file picker and viewer stay external-ui",
  },
  {
    id: "PEND-VIDEO-STREAM-001",
    title: "VideoContext setStreamSource against a stream provider",
    mode: "external-fixture",
    covers: ["VideoContext.setStreamSource"],
    reason: "needs a host stream provider addon; the Showcase has none",
  },
  {
    id: "PEND-NET-FIRE-001",
    title: "onNetworkChange fires, then unsubscribe is inert",
    mode: "external-fixture",
    covers: ["lx.onNetworkChange"],
    reason: "no injected network-change fixture; DEVICE-002 only toggles the listen flag",
  },
  {
    id: "PEND-ORIENT-EVT-001",
    title: "onDeviceOrientationChange fires after a host rotate",
    mode: "external-fixture",
    covers: ["lx.onDeviceOrientationChange"],
    reason: "LOGIC-002 only subscribe/unsubscribe; fire needs a rotate fixture",
  },
  {
    id: "PEND-WIFI-001",
    title: "connectWifi joins a network",
    mode: "external-fixture",
    covers: ["lx.connectWifi"],
    reason: "ANDROID-WIFI-001 covers the rest on a real radio; joining opens the system NetworkRequestDialog and would change the device's network, so it needs a lab access point",
  },
  {
    id: "PEND-APPLINK-001",
    title: "inbound App Link opens the declared lxapp",
    mode: "external-fixture",
    covers: ["lx.navigateToApp"],
    reason: "needs an /lxapp/open?appId= fixture host",
  },
  {
    id: "PEND-NATIVE-OVERLAY-001",
    title: "native modal and action sheet on a phone host",
    mode: "external-ui",
    covers: ["lx.showModal", "lx.showActionSheet"],
    reason: "a phone draws these natively, outside the page: the page cannot read them and only a system tap answers them; dismissing one with the system Back leaves the promise pending, so a spec that opened one would leak it",
  },
  {
    id: "PEND-NAVAPP-DESKTOP-001",
    title: "the cross-lxapp hop on a desktop host",
    mode: "planned",
    covers: ["lx.navigateToApp", "lx.navigateBackApp"],
    reason: "Windows leaves the target current after navigateBackApp instead of returning to the caller, and on both desktops the hop leaves the bundled chat lxapp in a state the workspace cases cannot reuse; NAV-APP-001 proves the contract on Android",
  },
  {
    id: "PEND-VIDEO-FS-WINDOWS-001",
    title: "native video fullscreen on Windows",
    mode: "planned",
    covers: ["VideoContext.requestFullScreen"],
    reason: "requestFullScreen rejects with an internal error on Windows while playback itself works; DESKTOP-VIDEO-FULLSCREEN-001 proves the contract on macOS",
  },
  {
    id: "PEND-PREVIEW-DISMISS-001",
    title: "dismissing the native preview settles completed",
    mode: "external-ui",
    covers: ["PreviewMediaHandle.completed"],
    reason: "the panel closes on a real gesture only: it outlives the page that opened it, an in-process AX invoke does not reach the host's own window, and a synthetic key lands wherever desktop focus is — DESKTOP-PREVIEW-MEDIA-001 proves presentation and the close control",
  },
  {
    id: "PEND-KEYS-001",
    title: "onKeyDown and onKeyUp fire from PageDriver.key",
    mode: "planned",
    covers: ["lx.onKeyDown", "lx.onKeyUp"],
    reason: "no case yet drives a host key into the listener",
  },
  {
    id: "PEND-PTR-GESTURE-001",
    title: "onPullDownRefresh fires from the native gesture",
    mode: "planned",
    covers: ["lx.startPullDownRefresh"],
    reason: "PULL-001 only clicks start/stop buttons",
  },
  {
    id: "PEND-APP-LIFE-001",
    title: "App onLaunch, onShow, and onHide if declared",
    mode: "planned",
    covers: ["lx.app.getBaseInfo"],
    reason: "App lifecycle hooks are not first-class covers yet",
  },
  {
    id: "PEND-STREAM-CANCEL-001",
    title: "stream cancel mid-flight runs generator finally",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "current stream.test.ts is happy-path only",
  },
  {
    id: "PEND-PICKER-001",
    title: "LxPicker value change, cancel, and columns",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 only opens the page",
  },
  {
    id: "PEND-NAVIGATOR-001",
    title: "LxNavigator open and back",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 only opens the page",
  },
  {
    id: "PEND-SWIPER-001",
    title: "LxMediaSwiper index change and add from chooseMedia",
    mode: "planned",
    covers: ["lx.chooseMedia"],
    reason: "add path is OS picker; index events have no contract",
  },
  {
    id: "PEND-PAGE-GLOBALS-001",
    title: "Page and App globals as first-class covers",
    mode: "planned",
    covers: ["lx.app.getBaseInfo"],
    reason: "setData / getApp / this.route / this.surface are not owned yet",
  },
  {
    id: "PEND-CHANNEL-ERR-001",
    title: "channel close, send-while-disconnected, and BRIDGE_NOT_READY",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "channel.test.ts covers happy reconnect only",
  },
  {
    id: "PEND-NATIVE-ATTR-001",
    title: "native component attributes and events beyond page open",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 does not assert attrs or CustomEvent detail",
  },
  {
    id: "PEND-ERR-CATALOG-001",
    title: "map SurfaceErrorCode, LxErrorCode, and BRIDGE_* to owners",
    mode: "planned",
    covers: ["lx.supports"],
    reason: "error catalog still has codes with zero test mentions",
  },
  {
    id: "PEND-BROWSER-DRV-001",
    title: "BrowserDriver tabs, eval, wait, and cookies",
    mode: "planned",
    covers: ["lx.shell.openBuiltin"],
    reason: "DESKTOP-BROWSER-001 does not cover cookies or wait",
  },
  {
    id: "PEND-DEVICE-DRV-001",
    title: "DeviceDriver get, list, and set",
    mode: "planned",
    covers: ["lx.getDeviceInfo"],
    reason: "automation DeviceDriver is still shape-only",
  },
  {
    id: "PEND-POINTER-001",
    title: "PagePointer and PageKey drag, down, and up",
    mode: "planned",
    covers: ["lx.automation"],
    reason: "only click/type are used as tools today",
  },
  {
    id: "PEND-DESKTOP-DRV-001",
    title: "DesktopClipboard and DesktopWindow as contracts",
    mode: "planned",
    covers: ["lx.automation"],
    reason: "used as helpers in workspace tests, not first-class specs",
  },
  {
    id: "PEND-VUE-TESTID-001",
    title: "Vue views carry every data-testid the React views expose",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "this Windows run is react-only; Vue testid parity is not gated",
  },
  {
    id: "PEND-VUE-MATRIX-001",
    title: "desktop contracts marked for Vue or macos-react-only",
    mode: "planned",
    covers: ["lx.surface.openDeclared"],
    reason: "desktop files never run under Vue in CI",
  },
  {
    id: "PEND-ANDROID-001",
    title: "wave-1 chrome cases on the Android shared entry",
    mode: "planned",
    covers: ["lx.navigationBar.update"],
    reason: "Android entry is shared-only; chrome cases are not required there yet",
  },
  {
    id: "PEND-ANDROID-DEV-001",
    title: "Android DeviceDriver, wifi landscape, and PTR gesture",
    mode: "planned",
    covers: ["lx.startWifi"],
    reason: "out of the Windows Showcase react run",
  },
  {
    id: "PEND-TRUSTED-001",
    title: "trustedDomains allow listed hosts and deny the rest",
    mode: "planned",
    covers: ["lx.getNetworkInfo"],
    reason: "no fetch allow/deny contract is registered",
  },
  {
    id: "PEND-PAGE-JSON-001",
    title: "page JSON enablePullDownRefresh and navigationStyle",
    mode: "planned",
    covers: ["lx.startPullDownRefresh"],
    reason: "page JSON vs app.info() is not asserted",
  },
  {
    id: "PEND-CLOUD-TESTID-001",
    title: "cloud page testids on both frameworks",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "pages/cloud still has no data-testid on either view",
  },
];
