/** Pending backlog items that must or are worth automating, but are not at the
 *  tests/README bar yet. Bodies stay empty (`spec.skip`); modes stay off
 *  `automated` in logic-api-coverage.mjs. */
export default [
  {
    id: "PEND-TERMINAL-API-001",
    title: "terminal settings, fonts, colour schemes, and Windows integration",
    mode: "external-fixture",
    covers: [
      "lx.terminal.settings",
      "lx.terminal.settings.get",
      "lx.terminal.settings.update",
      "lx.terminal.settings.reset",
      "lx.terminal.settings.onChange",
      "lx.terminal.fonts",
      "lx.terminal.fonts.list",
      "lx.terminal.colorSchemes",
      "lx.terminal.colorSchemes.list",
      "lx.terminal.colorSchemes.import",
      "lx.terminal.colorSchemes.createPreview",
      "lx.terminal.windows",
      "lx.terminal.windows.status",
      "lx.terminal.windows.install",
      "lx.terminal.windows.setEnabled",
    ],
    reason: "lx.terminal is present only in the host-bundled Terminal Settings lxapp; the Showcase cannot reach it",
  },
  {
    id: "PEND-DIRPICK-001",
    title: "chooseDirectory returns a grant the lxapp can read",
    mode: "external-ui",
    covers: ["lx.chooseDirectory"],
    reason: "the directory picker is an OS dialog with no in-process driver",
  },
  {
    id: "PEND-UPLOAD-001",
    title: "uploadFile progress, cancel, and the UploadTask contract",
    mode: "external-fixture",
    covers: [
      "lx.uploadFile",
      "UploadTask.then",
      "UploadTask.wait",
      "UploadTask.cancel",
    ],
    reason: "needs an upload endpoint the runner controls, so failure modes are deterministic",
  },
  {
    id: "PEND-DESTRUCTIVE-001",
    title: "exit, navigateBackApp, and applyUpdate end the session under test",
    mode: "planned",
    covers: ["lx.app.exit", "lx.navigateBackApp", "UpdateManager.applyUpdate"],
    reason: "each tears down the lxapp the suite is driving; they need a throwaway session per case",
  },
  {
    id: "PEND-UPDATE-INFO-001",
    title: "HostAppUpdateInfo fields from a real staged host update",
    mode: "external-fixture",
    covers: ["HostAppUpdateInfo.isForceUpdate"],
    reason: "needs a cloud provider serving a staged host build to populate the info",
  },
  {
    id: "PEND-SHARE-001",
    title: "share text, page, and files through the OS share sheet",
    mode: "external-ui",
    covers: ["lx.share"],
    reason: "OS share sheet cannot be driven without a device-lab UI helper",
  },
  {
    id: "PEND-LOCATION-001",
    title: "read coordinates or a stable deny code from getLocation",
    mode: "external-ui",
    covers: ["lx.getLocation"],
    reason: "permission sheet / location grant is host OS UI",
  },
  {
    id: "PEND-MEDIA-PICK-001",
    title: "chooseMedia, scanCode, and previewMedia through the real OS UI",
    mode: "external-ui",
    covers: [
      "lx.chooseMedia",
      "lx.scanCode",
      "lx.previewMedia",
      "PreviewMediaHandle.presented",
      "PreviewMediaHandle.onChange",
      "PreviewMediaHandle.completed",
    ],
    reason: "camera, picker, and native preview are OS dialogs",
  },
  {
    id: "PEND-PHOTOS-001",
    title: "save image and video into the photos album",
    mode: "external-ui",
    covers: ["lx.saveImageToPhotosAlbum", "lx.saveVideoToPhotosAlbum"],
    reason: "photos-library permission sheet is OS UI",
  },
  {
    id: "PEND-ORIENT-001",
    title: "setDeviceOrientation and observe the host rotate",
    mode: "external-ui",
    covers: ["lx.setDeviceOrientation"],
    reason: "host rotation / orientation lock is device-lab",
  },
  {
    id: "PEND-EXTERNAL-001",
    title: "openExternal launches the system browser",
    mode: "external-ui",
    covers: ["lx.openExternal"],
    reason: "system browser handoff cannot be asserted in-process",
  },
  {
    id: "PEND-DEVICE-FB-001",
    title: "vibrate and makePhoneCall, or reject with unsupported",
    mode: "external-ui",
    covers: ["lx.vibrateShort", "lx.vibrateLong", "lx.makePhoneCall"],
    reason: "haptics and the dialer are platform UI / unsupported on desktop",
  },
  {
    id: "PEND-MORE-ACTIONS-001",
    title: "setMoreActions overflow item opens the declared surface",
    mode: "external-ui",
    covers: ["lx.setMoreActions"],
    reason: "host chrome overflow menu is not exposed as a Logic contract yet",
  },
  {
    id: "PEND-FILE-PICK-001",
    title: "openFile and chooseFile cancel/error codes",
    mode: "external-ui",
    covers: ["lx.openFile", "lx.chooseFile"],
    reason: "OS file picker and viewer stay external-ui",
  },
  {
    id: "PEND-VIDEO-FS-001",
    title: "VideoContext requestFullScreen and exitFullScreen",
    mode: "external-ui",
    covers: ["lx.createVideoContext", "VideoContext.requestFullScreen"],
    reason: "fullscreen is a host chrome transition, not an in-page control",
  },
  {
    id: "PEND-NAVAPP-001",
    title: "navigateToApp opens or rejects with a stable code",
    mode: "external-fixture",
    covers: ["lx.navigateToApp"],
    reason: "needs a second-lxapp fixture beyond the live Showcase session",
  },
  {
    id: "PEND-DOWNLOAD-001",
    title: "downloadFile progress, pause, resume, cancel, and abort",
    mode: "external-fixture",
    covers: [
      "lx.downloadFile",
      "DownloadTask.next",
      "DownloadTask.pause",
      "DownloadTask.resume",
      "DownloadTask.cancel",
    ],
    reason: "generated type is never; needs an http download fixture",
  },
  {
    id: "PEND-OPENURL-001",
    title: "surface.openUrl and TabSurface activate/scope",
    mode: "external-fixture",
    covers: ["lx.surface.openUrl"],
    reason: "browser tab surface fixture is not wired in Showcase Logic tests",
  },
  {
    id: "PEND-SURFACE-MSG-001",
    title: "surface onContext and PageSurface onMessage",
    mode: "external-fixture",
    covers: ["PageSurface.onMessage"],
    reason: "ui-to-surface message port needs a dedicated child surface fixture",
  },
  {
    id: "PEND-VIDEO-CTRL-001",
    title: "VideoContext play, stop, seek, and setStreamSource",
    mode: "external-fixture",
    covers: ["VideoContext.play", "VideoContext.stop", "VideoContext.seek"],
    reason: "needs a real media source fixture; NATIVE-VIDEO-001 only hides overlay",
  },
  {
    id: "PEND-NET-FIRE-001",
    title: "onNetworkChange fires, then unsubscribe is inert",
    mode: "external-fixture",
    covers: ["lx.onNetworkChange"],
    reason: "no injected network-change fixture; DEVICE-002 only toggles the listen flag",
  },
  {
    id: "PEND-ORIENT-EVT-001",
    title: "onDeviceOrientationChange fires after a host rotate",
    mode: "external-fixture",
    covers: ["lx.onDeviceOrientationChange"],
    reason: "LOGIC-002 only subscribe/unsubscribe; fire needs a rotate fixture",
  },
  {
    id: "PEND-WIFI-001",
    title: "wifi start/stop/list/connect and onWifiConnected",
    mode: "external-fixture",
    covers: [
      "lx.onWifiConnected",
      "lx.startWifi",
      "lx.stopWifi",
      "lx.getWifiList",
      "lx.getConnectedWifi",
      "lx.connectWifi",
    ],
    reason: "android wifi fixture; desktop has no joinable radio in this suite",
  },
  {
    id: "PEND-MEDIA-INFO-001",
    title: "compress, thumbnail, getVideoInfo, and CompressVideoTask",
    mode: "external-fixture",
    covers: [
      "lx.getVideoInfo",
      "lx.extractVideoThumbnail",
      "lx.compressVideo",
      "lx.compressImage",
      "CompressVideoTask.wait",
      "CompressVideoTask.cancel",
    ],
    reason: "needs a checked-in media fixture larger than the shape check",
  },
  {
    id: "PEND-VIDEO-EVT-001",
    title: "LxVideo play, pause, timeupdate, and ended events",
    mode: "external-fixture",
    covers: ["lx.createVideoContext"],
    reason: "empty video fixture cannot emit real playback events",
  },
  {
    id: "PEND-APPLINK-001",
    title: "inbound App Link opens the declared lxapp",
    mode: "external-fixture",
    covers: ["lx.navigateToApp"],
    reason: "needs an /lxapp/open?appId= fixture host",
  },
  {
    id: "PEND-NAV-QUERY-001",
    title: "navigateTo query plus PageMessagePort",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "PageMessagePort is unused in Showcase Logic",
  },
  {
    id: "PEND-KEYS-001",
    title: "onKeyDown and onKeyUp fire from PageDriver.key",
    mode: "planned",
    covers: ["lx.onKeyDown", "lx.onKeyUp"],
    reason: "no case yet drives a host key into the listener",
  },
  {
    id: "PEND-PTR-GESTURE-001",
    title: "onPullDownRefresh fires from the native gesture",
    mode: "planned",
    covers: ["lx.startPullDownRefresh"],
    reason: "PULL-001 only clicks start/stop buttons",
  },
  {
    id: "PEND-APP-LIFE-001",
    title: "App onLaunch, onShow, and onHide if declared",
    mode: "planned",
    covers: ["lx.app.getBaseInfo"],
    reason: "App lifecycle hooks are not first-class covers yet",
  },
  {
    id: "PEND-STREAM-CANCEL-001",
    title: "stream cancel mid-flight runs generator finally",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "current stream.test.ts is happy-path only",
  },
  {
    id: "PEND-PICKER-001",
    title: "LxPicker value change, cancel, and columns",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 only opens the page",
  },
  {
    id: "PEND-NAVIGATOR-001",
    title: "LxNavigator open and back",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 only opens the page",
  },
  {
    id: "PEND-SWIPER-001",
    title: "LxMediaSwiper index change and add from chooseMedia",
    mode: "planned",
    covers: ["lx.chooseMedia"],
    reason: "add path is OS picker; index events have no contract",
  },
  {
    id: "PEND-PAGE-GLOBALS-001",
    title: "Page and App globals as first-class covers",
    mode: "planned",
    covers: ["lx.app.getBaseInfo"],
    reason: "setData / getApp / this.route / this.surface are not owned yet",
  },
  {
    id: "PEND-CHANNEL-ERR-001",
    title: "channel close, send-while-disconnected, and BRIDGE_NOT_READY",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "channel.test.ts covers happy reconnect only",
  },
  {
    id: "PEND-NATIVE-ATTR-001",
    title: "native component attributes and events beyond page open",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "COMPONENTS-001 does not assert attrs or CustomEvent detail",
  },
  {
    id: "PEND-ERR-CATALOG-001",
    title: "map SurfaceErrorCode, LxErrorCode, and BRIDGE_* to owners",
    mode: "planned",
    covers: ["lx.supports"],
    reason: "error catalog still has codes with zero test mentions",
  },
  {
    id: "PEND-BROWSER-DRV-001",
    title: "BrowserDriver tabs, eval, wait, and cookies",
    mode: "planned",
    covers: ["lx.shell.openBuiltin"],
    reason: "DESKTOP-BROWSER-001 does not cover cookies or wait",
  },
  {
    id: "PEND-DEVICE-DRV-001",
    title: "DeviceDriver get, list, and set",
    mode: "planned",
    covers: ["lx.getDeviceInfo"],
    reason: "automation DeviceDriver is still shape-only",
  },
  {
    id: "PEND-POINTER-001",
    title: "PagePointer and PageKey drag, down, and up",
    mode: "planned",
    covers: ["lx.automation"],
    reason: "only click/type are used as tools today",
  },
  {
    id: "PEND-DESKTOP-DRV-001",
    title: "DesktopClipboard and DesktopWindow as contracts",
    mode: "planned",
    covers: ["lx.automation"],
    reason: "used as helpers in workspace tests, not first-class specs",
  },
  {
    id: "PEND-VUE-TESTID-001",
    title: "Vue views carry every data-testid the React views expose",
    mode: "planned",
    covers: ["lx.navigateTo"],
    reason: "this Windows run is react-only; Vue testid parity is not gated",
  },
  {
    id: "PEND-VUE-MATRIX-001",
    title: "desktop contracts marked for Vue or macos-react-only",
    mode: "planned",
    covers: ["lx.surface.openDeclared"],
    reason: "desktop files never run under Vue in CI",
  },
  {
    id: "PEND-ANDROID-001",
    title: "wave-1 chrome cases on the Android shared entry",
    mode: "planned",
    covers: ["lx.navigationBar.update"],
    reason: "Android entry is shared-only; chrome cases are not required there yet",
  },
  {
    id: "PEND-ANDROID-DEV-001",
    title: "Android DeviceDriver, wifi landscape, and PTR gesture",
    mode: "planned",
    covers: ["lx.startWifi"],
    reason: "out of the Windows Showcase react run",
  },
  {
    id: "PEND-TRUSTED-001",
    title: "trustedDomains allow listed hosts and deny the rest",
    mode: "planned",
    covers: ["lx.getNetworkInfo"],
    reason: "no fetch allow/deny contract is registered",
  },
  {
    id: "PEND-PAGE-JSON-001",
    title: "page JSON enablePullDownRefresh and navigationStyle",
    mode: "planned",
    covers: ["lx.startPullDownRefresh"],
    reason: "page JSON vs app.info() is not asserted",
  },
  {
    id: "PEND-TERM-PREVIEW-001",
    title: "TerminalPreviewController createPreview, clear, show, close",
    mode: "planned",
    covers: ["lx.terminal"],
    reason: "typed controller has no SHAPE or behavior spec",
  },
  {
    id: "PEND-CLOUD-TESTID-001",
    title: "cloud page testids on both frameworks",
    mode: "planned",
    covers: ["lx.cloud"],
    reason: "pages/cloud still has no data-testid on either view",
  },
];
