// Lingxia WebView Bridge Client

(function () {
  const NATIVE_HANDLER_NAME = "LingXia"; // iOS: window.webkit.messageHandlers name
  const GLOBAL_RECEIVER_NAME = "__LingXiaRecvMessage"; // iOS: Global function called by Native
  const CALL_TIMEOUT_MS = 5000;
  const LOG_PREFIX = "[LingxiaBridge]";
  const ANDROID_PORT_INIT_CMD = "LingXia-port-init"; // Android: Native command to send MessagePort

  let messageCounter = 0;
  const pendingCalls = new Map(); // msgId -> { resolve, reject, timerId }
  let pageData = {};
  const dataSubscribers = new Set();
  let androidMessagePort = null;

  const isIOS = !!(
    window.webkit &&
    window.webkit.messageHandlers &&
    window.webkit.messageHandlers[NATIVE_HANDLER_NAME]
  );
  const isAndroid = !isIOS;

  function log(...args) {
    console.log(LOG_PREFIX, ...args);
  }
  function warn(...args) {
    console.warn(LOG_PREFIX, ...args);
  }
  function error(...args) {
    console.error(LOG_PREFIX, ...args);
  }

  // Creates an isolated copy of data passed to subscribers / getCurrentData callers.
  function deepCopy(data) {
    try {
      if (typeof structuredClone === "function") {
        return structuredClone(data);
      } else {
        return JSON.parse(JSON.stringify(data));
      }
    } catch (e) {
      error("Failed to deep copy data:", e);
      return {};
    }
  }

  // Helper to set value by path, needed for applyPatch
  function _setValueByPath(obj, path, value) {
    if (typeof path !== "string" || path === "") {
      warn("Invalid path:", path);
      return false;
    }
    if (typeof obj !== "object" || obj === null) {
      warn("Invalid target object");
      return false;
    }

    const parts = path.replace(/\[(\d+)\]/g, ".$1").split(".");
    let current = obj;

    for (let i = 0; i < parts.length - 1; i++) {
      const key = parts[i];
      const nextKey = parts[i + 1];
      const isNextKeyArrayIndex = /^\d+$/.test(nextKey);

      if (current[key] === undefined || current[key] === null) {
        current[key] = isNextKeyArrayIndex ? [] : {};
      } else if (typeof current[key] !== "object") {
        warn(`Overwriting non-object path segment "${key}"`);
        current[key] = isNextKeyArrayIndex ? [] : {};
      } else if (isNextKeyArrayIndex && !Array.isArray(current[key])) {
        warn(`Overwriting non-array segment "${key}" with an array`);
        current[key] = [];
      }
      current = current[key];
      if (typeof current !== "object" || current === null) {
        error(`Cannot set path further at segment "${key}".`);
        return false;
      }
    }

    const finalKey = parts[parts.length - 1];
    current[finalKey] = value;
    return true;
  }

  // Helper to delete value by path, needed for applyPatch
  function _deleteValueByPath(obj, path) {
    if (typeof path !== "string" || path === "") {
      warn("Invalid delete path:", path);
      return false;
    }
    if (typeof obj !== "object" || obj === null) {
      warn("Invalid target object");
      return false;
    }

    const parts = path.replace(/\[(\d+)\]/g, ".$1").split(".");
    let current = obj;

    for (let i = 0; i < parts.length - 1; i++) {
      const key = parts[i];
      if (typeof current[key] !== "object" || current[key] === null) {
        warn(`Path segment "${key}" not found or not object for deletion.`);
        return false; // Cannot traverse further
      }
      current = current[key];
    }

    const finalKey = parts[parts.length - 1];
    if (Array.isArray(current)) {
      const index = parseInt(finalKey, 10);
      if (!isNaN(index) && index >= 0 && index < current.length) {
        current.splice(index, 1); // Use splice for array element deletion
        return true;
      }
    } else if (typeof current === "object") {
      delete current[finalKey]; // Use delete for object properties
      return true;
    }
    return false;
  }

  /**
   * Applies a patch object (generated by the diff function) to a target object.
   * @param {object} target - The object to modify.
   * @param {object} patch - The patch object { 'path.string': value, ... }.
   */
  function _applyPatch(target, patch) {
    if (typeof target !== "object" || target === null) {
      error("ApplyPatch: Invalid target object.");
      return;
    }
    if (typeof patch !== "object" || patch === null) {
      error("ApplyPatch: Invalid patch object.");
      return;
    }

    let changesApplied = false;
    for (const path in patch) {
      if (Object.prototype.hasOwnProperty.call(patch, path)) {
        const value = patch[path];
        if (value === undefined) {
          // Handle deletion
          if (_deleteValueByPath(target, path)) {
            changesApplied = true;
            log(`Deleted path: ${path}`);
          } else {
            warn(`Failed to delete path: ${path}`);
          }
        } else {
          // Handle set/update
          if (_setValueByPath(target, path, value)) {
            changesApplied = true;
            log(`Set path: ${path}`);
          } else {
            warn(`Failed to set path: ${path}`);
          }
        }
      }
    }
    return changesApplied;
  }

  function _sendMessageToNative(message) {
    try {
      if (isIOS) {
        window.webkit.messageHandlers[NATIVE_HANDLER_NAME].postMessage(message);
      } else if (isAndroid && androidMessagePort) {
        const messageString = JSON.stringify(message);
        androidMessagePort.postMessage(messageString);
      } else {
        warn("Bridge not configured for sending or Android port not ready.", {
          isIOS,
          isAndroid,
          hasAndroidPort: !!androidMessagePort,
        });
      }
    } catch (e) {
      error("Send message error:", e, message);
    }
  }

  function _handleIncomingMessage(message) {
    log(
      "Message Received:",
      typeof message === "object" ? JSON.stringify(message) : message,
    );
    if (!message || typeof message !== "object" || !message.type) {
      warn("Received invalid message format:", message);
      return;
    }

    switch (message.type) {
      case "reply":
        _handleReply(message);
        break;
      case "call":
        _handleCall(message);
        break;
      default:
        warn("Received unknown message type:", message.type, message);
    }
  }

  function _handleReply(replyMessage) {
    const msgId = replyMessage.msgId;
    if (!msgId || !pendingCalls.has(msgId)) {
      warn("Reply for unknown msgId:", replyMessage);
      return;
    }

    const callInfo = pendingCalls.get(msgId);
    pendingCalls.delete(msgId);
    clearTimeout(callInfo.timerId);

    try {
      if (replyMessage.payload?.success === true) {
        callInfo.resolve();
      } else if (replyMessage.payload?.success === false) {
        callInfo.reject(
          replyMessage.payload.error || {
            message: "Unknown Logic Layer error",
          },
        );
      } else {
        warn("Invalid reply payload:", replyMessage);
        callInfo.reject({ message: "Invalid reply payload" });
      }
    } catch (e) {
      error("Reply processing error:", e, replyMessage);
      try {
        callInfo.reject({ message: `Reply handler error: ${e.message}` });
      } catch (_) {}
    }
  }

  function _handleCall(callMessage) {
    const { msgId, name, payload } = callMessage;

    if (!msgId) {
      warn("Call without msgId:", callMessage);
      return;
    }
    if (!name) {
      warn("Call without name:", callMessage);
      _sendReply(msgId, false, { message: "Call missing 'name' field." });
      return;
    }

    try {
      if (name === "setData") {
        let dataToApply;
        let callbackId = null;

        if (payload && typeof payload.data !== "undefined") {
          dataToApply = payload.data;
          callbackId = payload.callbackId;
        } else {
          dataToApply = payload;
        }

        _applyPatch(pageData, dataToApply);

        setTimeout(() => {
          const dataCopy = deepCopy(pageData);
          dataSubscribers.forEach((listener) => {
            try {
              listener(dataCopy, callbackId);
            } catch (e) {
              error("Data subscriber error:", e);
            }
          });
        }, 0);

        _sendReply(msgId, true);
      } else {
        warn(`Unhandled call '${name}':`, callMessage);
        _sendReply(msgId, false, { message: `Unhandled call '${name}'.` });
      }
    } catch (e) {
      error(`Call handler error '${name}':`, e, callMessage);
      _sendReply(msgId, false, { message: `View handler error: ${e.message}` });
    }
  }

  function _sendReply(originalMsgId, success, errorPayload = null) {
    const replyPayload = success
      ? { success: true }
      : {
          success: false,
          error: errorPayload || { message: "Unknown view error" },
        };
    _sendMessageToNative({
      msgId: originalMsgId,
      type: "reply",
      payload: replyPayload,
    });
  }

  const LingXiaBridge = {
    /**
     * Call a function in the Logic Layer.
     * @param {string} name - Function name.
     * @param {object|null} payload - Function arguments.
     * @returns {Promise<void>}
     */
    call: function (name, payload = null) {
      return new Promise((resolve, reject) => {
        const msgId = `view-${Date.now()}-${messageCounter++}`;
        const timerId = setTimeout(() => {
          if (pendingCalls.has(msgId)) {
            warn(`Timeout msgId: ${msgId}, name: ${name}`);
            pendingCalls
              .get(msgId)
              .reject({ message: `Call '${name}' timed out` });
            pendingCalls.delete(msgId);
          }
        }, CALL_TIMEOUT_MS);
        pendingCalls.set(msgId, { resolve, reject, timerId });
        _sendMessageToNative({
          msgId: msgId,
          type: "call",
          name: name,
          payload: payload,
        });
      });
    },

    /**
     * Send a fire-and-forget event to the Logic Layer.
     * @param {string} name - Event name.
     * @param {object|null} payload - Event data.
     */
    event: function (name, payload = null) {
      _sendMessageToNative({
        msgId: null,
        type: "event",
        name: name,
        payload: payload,
      });
    },

    /**
     * Subscribe to page data updates from the Logic Layer.
     * @param {function(object): void} listenerCallback - Called with a deep copy of the updated data.
     * @returns {function(): void} - Function to unsubscribe.
     */
    subscribe: function (listenerCallback) {
      if (typeof listenerCallback !== "function") {
        error("Subscriber must be a function.");
        return () => {};
      }
      dataSubscribers.add(listenerCallback);
      log("Subscriber added");
      return () => {
        dataSubscribers.delete(listenerCallback);
        log("Subscriber removed");
      };
    },

    /**
     * Get a deep copy of the current page data.
     * @returns {object}
     */
    getCurrentData: function () {
      return deepCopy(pageData);
    },

    // Internal method called by platform-specific setup
    _connectAndroidPort: function (port) {
      if (!isAndroid) return;

      // Always use the new port. If there was an old one, it's implicitly replaced.
      // The native side is responsible for managing the lifecycle of its end of the previous port.
      androidMessagePort = port;

      androidMessagePort.onmessage = (event) => {
        let messageData = event.data;
        if (typeof messageData === "string") {
          try {
            messageData = JSON.parse(messageData);
          } catch (e) {
            error("Invalid JSON from Android Port:", e, event.data);
            return;
          }
        } else {
          warn(
            "Received non-string data from Android Port. Attempting to process as is:",
            messageData,
          );
        }
        _handleIncomingMessage(messageData);
      };

      try {
        // Send LXPortRdy event over the NEWLY connected port
        this.event("LXPortRdy");
        log("Android MessagePort (re)connected and LXPortRdy event sent.");
      } catch (e) {
        error("Failed to send LXPortRdy event via new Android Port:", e);
      }
    },

    // Internal method called by platform-specific setup
    _receiveIOsMessage: function (messageString) {
      if (!isIOS) return;
      try {
        if (!messageString) {
          warn("Empty msg from iOS.");
          return;
        }
        const message = JSON.parse(messageString);
        _handleIncomingMessage(message);
      } catch (e) {
        error("Invalid JSON from iOS:", e, messageString);
      }
    },

    /**
     * Called by data subscribers (e.g., UI frameworks) after they have processed
     * a data update associated with a callbackId and wish to trigger the callback in the Logic Layer.
     * @param {string} callbackId - The ID originally provided with the setData call.
     */
    resolveCallback: function (callbackId) {
      if (typeof callbackId !== "string" || !callbackId) {
        error("resolveCallback: callbackId must be a non-empty string.");
        return;
      }

      _sendMessageToNative({
        msgId: null,
        type: "callback",
        callbackId: callbackId,
      });
    },
  };

  // Platform Initialization
  if (isIOS) {
    window[GLOBAL_RECEIVER_NAME] = LingXiaBridge._receiveIOsMessage;

    try {
      // Use setTimeout to ensure sending after initialization completes
      setTimeout(() => {
        LingXiaBridge.event("LXPortRdy");
        log("iOS LXPortRdy event sent.");
      }, 0);
    } catch (e) {
      error("Failed to send LXPortRdy event for iOS:", e);
    }
  }

  if (isAndroid) {
    // Listen for the MessagePort from Native
    window.addEventListener(
      "message",
      (event) => {
        if (
          event.data === ANDROID_PORT_INIT_CMD &&
          event.ports &&
          event.ports.length > 0
        ) {
          log("Android port init received from native.");
          LingXiaBridge._connectAndroidPort(event.ports[0]);
        }
      },
      false,
    );
    log("Android port listener ready.");
  }

  window.LingXiaBridge = LingXiaBridge;
  log("Lingxia WebView Bridge initialized.");
})();
