//! Host app metadata, state paths, and app-level lifecycle helpers.
//!
//! These APIs describe the native host application, not an individual LxApp
//! page. They are intended for Rust native code built with LingXia, including
//! code generated by `lingxia::native`.
//!
//! Common uses:
//!
//! - read product metadata such as `product_version` and `lingxia_id`;
//! - resolve host-owned state paths such as `state_dir` and `state_file`;
//! - read, follow or set the display language and the light/dark appearance;
//! - follow whether the app is in the foreground;
//! - request host app termination with `exit`.
//!
//! # Observable values
//!
//! Every value that changes at run time has the same three forms:
//!
//! | Value | Read | Callback | Async |
//! |---|---|---|---|
//! | foreground | [`is_foreground`] | [`watch_foreground`] | [`foreground_changes`] |
//! | display language | [`display_language`] | [`watch_display_language`] | [`display_language_changes`] |
//! | its preference | [`display_language_preference`] | [`watch_display_language_preference`] | [`display_language_preference_changes`] |
//! | light/dark | [`appearance`] | [`watch_appearance`] | [`appearance_changes`] |
//! | its preference | [`appearance_preference`] | [`watch_appearance_preference`] | [`appearance_preference_changes`] |
//!
//! A `watch_*` callback is called first with the current value, then once per
//! actual change. The first call and every change travel the same ordered
//! path, so nothing falls between registering and the first call. It returns
//! a [`Subscription`]: dropping it unsubscribes, [`Subscription::detach`]
//! keeps the callback for the process.
//!
//! Callbacks run one at a time, in order, on a LingXia delivery thread: never
//! inside `watch_*` itself, never on the platform main thread, and with no
//! LingXia lock held, so a callback may call any `lingxia` API. Each area has
//! its own thread (foreground; display language and its preference;
//! appearance and its preference), so ordering is per value and a slow
//! foreground callback does not hold up a language change; within an area a
//! slow callback delays the ones after it. Since calls never overlap, a
//! callback is an `FnMut` and may keep its own state. The argument is the value
//! at that change; the getter may already be newer. A panicking callback is
//! logged and the others still run.
//!
//! Dropping a [`Subscription`] never waits: no new call starts after it, and a
//! call already running finishes on the delivery thread. A callback may drop
//! its own `Subscription`.
//!
//! A `*_changes()` [`Changes`] stream yields the current value, then each
//! change. A consumer that falls behind gets the latest value, not a backlog.
//! It never ends, so `changes.next().await` returns the value itself.
//!
//! ```no_run
//! let subscription = lingxia::app::watch_foreground(|foreground| {
//!     println!("foreground: {foreground}");
//! });
//! subscription.detach();
//! ```
//!
//! ## Background grace
//!
//! On iOS and HarmonyOS, the callbacks for a move to the background run inside
//! an OS-granted grace period that LingXia holds until every one of them has
//! returned, so a callback can flush state or close connections before the
//! process is suspended. The OS bounds that time (a few seconds), and
//! [`Changes`] streams are not covered: work that must finish belongs in a
//! callback. Android does not suspend a started process this way.
//!
//! Android reports foreground only through activity start and stop, so a
//! process started without one (a push, a `JobService`) reads `true` until an
//! activity starts and stops.

use std::path::{Component, Path, PathBuf};
use std::sync::{Once, OnceLock};

use lingxia_platform::traits::app_runtime::AppRuntime;

pub use lingxia_app_context::{AppEnv, ServiceEnvSnapshot as ServiceEnvState};
pub use lxapp::page_chrome::{AppearancePreference, ResolvedAppearance};
pub use lxapp::{
    DisplayLanguageEffectiveSource, DisplayLanguagePreference, DisplayLanguageState, LanguageTag,
};

mod observe;
pub use observe::{Changes, Subscription};
use observe::{Delivery, Observable};

static APP_DATA_DIR: OnceLock<PathBuf> = OnceLock::new();

pub(crate) fn set_data_dir(path: PathBuf) {
    let _ = APP_DATA_DIR.set(path);
}

/// Returns the host app's display name from the initialized app config.
pub fn product_name() -> Option<&'static str> {
    lingxia_app_context::product_name()
}

/// Returns the host app version from the initialized app config.
pub fn product_version() -> Option<&'static str> {
    lingxia_app_context::product_version()
}

/// Returns the host deployment environment baked into the running product.
pub fn env() -> AppEnv {
    lingxia_app_context::env()
}

/// Effective service environment for this process (override or build env).
pub fn service_env() -> AppEnv {
    lingxia_app_context::service_env()
}

/// Current and next-launch service environments, with available targets.
pub fn service_env_state() -> ServiceEnvState {
    lingxia_app_context::service_env_snapshot()
}

/// The environment is saved for the next launch even if requesting exit fails.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToggleServiceEnvResult {
    pub state: ServiceEnvState,
    pub exit_requested: bool,
    /// When present, ask the user to close and reopen the app manually.
    pub exit_error: Option<String>,
}

/// Save the other service environment and request exit. A dev build cannot switch.
/// Retrying after an exit failure keeps the same target until the next launch.
/// Inspect `exit_error` to offer a manual restart when the platform cannot exit.
pub fn toggle_service_env() -> crate::Result<ToggleServiceEnvResult> {
    let state = lingxia_app_context::prepare_toggle().map_err(service_env_error)?;
    let exit_error = exit().err().map(|err| err.to_string());
    Ok(ToggleServiceEnvResult {
        state,
        exit_requested: exit_error.is_none(),
        exit_error,
    })
}

fn service_env_error(error: lingxia_app_context::ServiceEnvError) -> crate::Error {
    match error {
        lingxia_app_context::ServiceEnvError::NotInitialized => {
            crate::Error::internal(error.to_string())
        }
        lingxia_app_context::ServiceEnvError::Invalid(detail) => {
            crate::Error::invalid_request(detail)
        }
        lingxia_app_context::ServiceEnvError::Persist(detail) => crate::Error::internal(detail),
    }
}

/// Returns the configured home LxApp id from the initialized app config.
pub fn home_app_id() -> Option<&'static str> {
    lingxia_app_context::home_app_id()
}

#[cfg(any(target_os = "ios", target_os = "macos", target_os = "windows"))]
pub(crate) fn launch_home_control_logic() -> crate::Result<()> {
    let app_id =
        home_app_id().ok_or_else(|| crate::Error::internal("home lxapp is not configured"))?;
    let app = lxapp::try_get(app_id)
        .ok_or_else(|| crate::Error::internal(format!("home lxapp '{app_id}' is not ready")))?;
    app.ensure_app_service_running()
        .map_err(|error| crate::Error::internal(error.to_string()))?;
    app.ensure_app_launch_dispatched()
        .map_err(|error| crate::Error::internal(error.to_string()))
}

/// Returns the configured LingXia host identifier, if any.
pub fn lingxia_id() -> Option<&'static str> {
    lingxia_app_context::lingxia_id()
}

/// Reports whether push-notification capability is enabled for the host app.
pub fn notifications_enabled() -> bool {
    lingxia_app_context::notifications_enabled()
}

// One delivery thread per area, started on first use: a foreground callback
// holding the background grace must not stall language or appearance ones.
static FOREGROUND_DELIVERY: Delivery = Delivery::new("lingxia-app-foreground");
static LANGUAGE_DELIVERY: Delivery = Delivery::new("lingxia-app-language");
static APPEARANCE_DELIVERY: Delivery = Delivery::new("lingxia-app-appearance");
static FOREGROUND: Observable<bool> = Observable::new(&FOREGROUND_DELIVERY, Some(true));
static DISPLAY_LANGUAGE: Observable<LanguageTag> = Observable::new(&LANGUAGE_DELIVERY, None);
static DISPLAY_LANGUAGE_PREFERENCE: Observable<DisplayLanguagePreference> =
    Observable::new(&LANGUAGE_DELIVERY, None);
static APPEARANCE: Observable<ResolvedAppearance> = Observable::new(&APPEARANCE_DELIVERY, None);
static APPEARANCE_PREFERENCE: Observable<AppearancePreference> =
    Observable::new(&APPEARANCE_DELIVERY, None);

/// The effective host display language.
///
/// A pinned [`DisplayLanguagePreference::LanguageTag`] takes precedence over
/// the native host locale. [`DisplayLanguagePreference::Auto`] follows it.
pub fn display_language() -> LanguageTag {
    lxapp::display_language_state().effective
}

/// Follow [`display_language`]; see [the module docs](self#observable-values).
pub fn watch_display_language(listener: impl FnMut(LanguageTag) + Send + 'static) -> Subscription {
    display_language_source();
    DISPLAY_LANGUAGE.watch(listener)
}

/// [`display_language`], then each change.
pub fn display_language_changes() -> Changes<LanguageTag> {
    display_language_source();
    DISPLAY_LANGUAGE.changes()
}

/// What the user chose: `Auto`, or a pinned tag.
pub fn display_language_preference() -> DisplayLanguagePreference {
    lxapp::display_language_state().preference
}

/// Persist the product's display language and publish it after the write succeeds.
pub fn set_display_language_preference(preference: DisplayLanguagePreference) -> crate::Result<()> {
    lxapp::set_display_language_preference_in(&data_dir()?, preference).map_err(Into::into)
}

/// Follow the choice, not what it resolves to: a system locale change under
/// `Auto` moves the effective tag without moving the preference. See
/// [the module docs](self#observable-values).
pub fn watch_display_language_preference(
    listener: impl FnMut(DisplayLanguagePreference) + Send + 'static,
) -> Subscription {
    display_language_source();
    DISPLAY_LANGUAGE_PREFERENCE.watch(listener)
}

/// [`display_language_preference`], then each change.
pub fn display_language_preference_changes() -> Changes<DisplayLanguagePreference> {
    display_language_source();
    DISPLAY_LANGUAGE_PREFERENCE.changes()
}

/// Feed both display-language values from the service, once. Registration and
/// its starting state are taken under one lock.
fn display_language_source() {
    static INSTALLED: Once = Once::new();
    INSTALLED.call_once(|| {
        let start = lxapp::observe_display_language_state(Box::new(publish_display_language));
        publish_display_language(start);
    });
}

fn publish_display_language(update: lxapp::DisplayLanguageStateUpdate) {
    DISPLAY_LANGUAGE.offer(update.revision, update.state.effective);
    DISPLAY_LANGUAGE_PREFERENCE.offer(update.revision, update.state.preference);
}

/// What the host's light/dark setting resolves to now. Under
/// [`AppearancePreference::Auto`] this follows the system.
pub fn appearance() -> ResolvedAppearance {
    lxapp::host_appearance_state().resolved
}

/// Follow [`appearance`]; see [the module docs](self#observable-values).
///
/// The first appearance watcher in the process (this, [`appearance_changes`]
/// or the preference forms) reads the starting state like [`appearance`]
/// does, which under `Auto` on Apple is a synchronous hop to the main thread;
/// later ones reuse the cached value. Other platforms read it in place.
pub fn watch_appearance(listener: impl FnMut(ResolvedAppearance) + Send + 'static) -> Subscription {
    appearance_source();
    APPEARANCE.watch(listener)
}

/// [`appearance`], then each change.
pub fn appearance_changes() -> Changes<ResolvedAppearance> {
    appearance_source();
    APPEARANCE.changes()
}

/// What the user chose: `Auto`, `Light` or `Dark`.
pub fn appearance_preference() -> AppearancePreference {
    lxapp::host_appearance_state().preference
}

/// Persist the product's light/dark setting and apply it. Native chrome (tab
/// bar, navigation bar, status bar) and every lxapp that has not pinned its
/// own scheme in its manifest follow it.
pub fn set_appearance_preference(preference: AppearancePreference) -> crate::Result<()> {
    lxapp::set_host_appearance_preference(preference)
        .map(|_| ())
        .map_err(Into::into)
}

/// Follow [`appearance_preference`]; see [the module docs](self#observable-values).
pub fn watch_appearance_preference(
    listener: impl FnMut(AppearancePreference) + Send + 'static,
) -> Subscription {
    appearance_source();
    APPEARANCE_PREFERENCE.watch(listener)
}

/// [`appearance_preference`], then each change.
pub fn appearance_preference_changes() -> Changes<AppearancePreference> {
    appearance_source();
    APPEARANCE_PREFERENCE.changes()
}

/// Feed both appearance values. The observer is registered once, before the
/// starting state is read. Once seeded the observer keeps them current, so only
/// the first callers read the state, outside the `Once`: resolving `auto` may
/// wait on the main thread, which may be the next caller.
fn appearance_source() {
    static INSTALLED: Once = Once::new();
    INSTALLED.call_once(|| lxapp::observe_host_appearance(Box::new(publish_appearance)));
    if APPEARANCE.get().is_none() || APPEARANCE_PREFERENCE.get().is_none() {
        publish_appearance(lxapp::host_appearance_update());
    }
}

fn publish_appearance(update: lxapp::HostAppearanceUpdate) {
    APPEARANCE.offer(update.revision, update.state.resolved);
    APPEARANCE_PREFERENCE.offer(update.revision, update.state.preference);
}

/// Whether the host app is in the foreground, for the whole process rather
/// than one LxApp.
///
/// Mobile hosts report the OS lifecycle: iOS counts any connected scene that
/// is foreground (active or inactive, so a system alert or permission prompt
/// is not a background), Android counts started activities, HarmonyOS uses
/// the application state. Desktop hosts are always foreground. The value
/// starts `true` and moves when the platform first reports otherwise, so an
/// Android process started without an activity (a push, a `JobService`) reads
/// `true` until one starts and stops.
///
/// This is the process, not an lxapp: switching between lxapps fires their
/// `onShow`/`onHide` but never changes this value.
pub fn is_foreground() -> bool {
    FOREGROUND.get().unwrap_or(true)
}

/// Follow [`is_foreground`]; see [the module docs](self#observable-values).
/// On iOS and HarmonyOS, the `false` call runs inside the
/// [background grace](self#background-grace).
pub fn watch_foreground(listener: impl FnMut(bool) + Send + 'static) -> Subscription {
    FOREGROUND.watch(listener)
}

/// [`is_foreground`], then each change. Not covered by the
/// [background grace](self#background-grace).
pub fn foreground_changes() -> Changes<bool> {
    FOREGROUND.changes()
}

/// The entry point the platform bridges feed. Repeats are dropped here.
#[cfg_attr(
    not(any(
        target_os = "ios",
        target_os = "macos",
        target_os = "android",
        target_env = "ohos"
    )),
    allow(dead_code)
)]
pub(crate) fn set_foreground(foreground: bool) {
    FOREGROUND.set(foreground);
}

/// [`set_foreground`] holding an OS grace period: `release` runs once every
/// callback for this transition (and any queued before it) has returned. If
/// the delivery thread could not start, `release` waits queued for the next
/// transition to retry it; the platform's expiry handler ends the grace first.
#[cfg_attr(
    not(any(target_os = "ios", target_os = "macos", target_env = "ohos")),
    allow(dead_code)
)]
pub(crate) fn set_foreground_with_grace(foreground: bool, release: impl FnOnce() + Send + 'static) {
    FOREGROUND.set_then(foreground, release);
}

pub(crate) fn data_dir() -> crate::Result<PathBuf> {
    APP_DATA_DIR
        .get()
        .cloned()
        .ok_or_else(|| crate::Error::internal("app data directory is not initialized"))
}

/// Returns the host-owned state directory.
pub fn state_dir() -> crate::Result<PathBuf> {
    Ok(lingxia_app_context::app_state_dir(&data_dir()?))
}

/// Returns the full path to a file inside the host-owned state directory.
pub fn state_file(name: &str) -> crate::Result<PathBuf> {
    state_file_in(data_dir()?, name)
}

/// Returns the state directory for a specific running [`crate::LxApp`].
pub fn state_dir_for(app: &crate::LxApp) -> PathBuf {
    lingxia_app_context::app_state_dir(&app.user_data_dir)
}

/// Returns a file path inside an [`crate::LxApp`]'s state directory.
pub fn state_file_for(app: &crate::LxApp, name: &str) -> crate::Result<PathBuf> {
    state_file_in(&app.user_data_dir, name)
}

/// OS local notifications, for native hosts that have no JS Logic.
///
/// The same contract `lx.host.notification` exposes: `id` is the replace key,
/// and a tap resolves through [`crate::navigation`], so a native host can send
/// the user to a native screen without inventing a product URL for it.
pub mod notification {
    pub use lingxia_platform::traits::app_runtime::LocalNotificationStatus;
    use lingxia_platform::traits::app_runtime::{AppRuntime, LocalNotificationShow};
    use lingxia_service::navigation::{self, NavigationTarget, intent};

    /// One notification to post or replace.
    pub struct Notification {
        id: String,
        title: String,
        body: String,
        target: NavigationTarget,
        deliver_at_ms: Option<u64>,
        silent: bool,
    }

    impl Notification {
        /// `id` is the replace key: anything pending or delivered under it is
        /// replaced, and its old target stops resolving.
        pub fn new(id: impl Into<String>, title: impl Into<String>) -> Self {
            Self {
                id: id.into(),
                title: title.into(),
                body: String::new(),
                target: NavigationTarget::Activate,
                deliver_at_ms: None,
                silent: false,
            }
        }

        pub fn body(mut self, body: impl Into<String>) -> Self {
            self.body = body.into();
            self
        }

        /// Where the tap goes. Without one the product simply comes forward.
        pub fn target(mut self, target: NavigationTarget) -> Self {
            self.target = target;
            self
        }

        /// Epoch milliseconds. A time that is not in the future means now.
        pub fn deliver_at_ms(mut self, at_ms: u64) -> Self {
            self.deliver_at_ms = Some(at_ms);
            self
        }

        pub fn silent(mut self, silent: bool) -> Self {
            self.silent = silent;
            self
        }
    }

    /// The same capability gate the JS API answers to: a host that did not
    /// declare `capabilities.notifications` has no notification API at all,
    /// in Rust or in Logic.
    fn require_capability() -> crate::Result<()> {
        if lingxia_app_context::capability::notifications() {
            return Ok(());
        }
        Err(crate::Error::invalid_request(
            "this host did not declare capabilities.notifications",
        ))
    }

    /// `"granted"`, `"denied"`, or `"default"`. Never prompts.
    pub fn permission() -> crate::Result<String> {
        require_capability()?;
        crate::runtime::platform()?
            .notification_permission()
            .map_err(crate::Error::from)
    }

    /// Prompts where the OS has a prompt; otherwise reports the setting.
    pub fn request_permission() -> crate::Result<String> {
        require_capability()?;
        crate::runtime::platform()?
            .notification_request_permission()
            .map_err(crate::Error::from)
    }

    /// Post or replace. The target is validated before anything is persisted
    /// or handed to the OS, so an unknown route fails here rather than on tap.
    pub fn show(request: Notification) -> crate::Result<LocalNotificationStatus> {
        require_capability()?;
        if request.id.trim().is_empty() {
            return Err(crate::Error::invalid_request("notification id is empty"));
        }
        if request.title.trim().is_empty() {
            return Err(crate::Error::invalid_request("notification title is empty"));
        }
        navigation::validate(&request.target)
            .map_err(|error| crate::Error::invalid_request(error.to_string()))?;
        let platform = crate::runtime::platform()?;
        let staged = intent::stage(&request.id, &request.target)
            .map_err(|error| crate::Error::internal(error.to_string()))?;
        let outcome = platform.notification_show(&LocalNotificationShow {
            id: request.id,
            title: request.title,
            body: request.body,
            activation_token: staged.token.clone(),
            deliver_at_ms: request.deliver_at_ms,
            silent: request.silent,
        });
        match outcome {
            // Suppressed posts nothing, so nothing may resolve this token.
            Ok(LocalNotificationStatus::Suppressed) => {
                intent::rollback(&staged);
                Ok(LocalNotificationStatus::Suppressed)
            }
            Ok(status) => {
                intent::commit(&staged);
                Ok(status)
            }
            Err(error) => {
                intent::rollback(&staged);
                Err(crate::Error::from(error))
            }
        }
    }

    /// Remove what is pending or delivered under `id`, and retire its target.
    pub fn cancel(id: &str) -> crate::Result<()> {
        require_capability()?;
        intent::invalidate(id);
        crate::runtime::platform()?
            .notification_cancel(id)
            .map_err(crate::Error::from)
    }

    pub fn cancel_all() -> crate::Result<()> {
        require_capability()?;
        intent::invalidate_all();
        crate::runtime::platform()?
            .notification_cancel_all()
            .map_err(crate::Error::from)
    }
}

/// Product-drawn desktop banner (top-right). Not an OS notification.
pub mod banner {
    use lingxia_platform::traits::app_runtime::AppRuntime;
    pub use lingxia_platform::traits::app_runtime::{
        DesktopBannerAction, DesktopBannerActionStyle, DesktopBannerBackground,
        DesktopBannerOutcome, DesktopBannerShow,
    };

    /// Present a banner and wait until it is answered, dismissed, timed out, or replaced.
    pub fn show(request: DesktopBannerShow) -> crate::Result<DesktopBannerOutcome> {
        crate::runtime::platform()?
            .banner_show(&request)
            .map_err(crate::Error::from)
    }

    /// Dismiss a visible or queued banner. Unknown ids are fine.
    pub fn dismiss(id: &str) -> crate::Result<()> {
        crate::runtime::platform()?
            .banner_dismiss(id)
            .map_err(crate::Error::from)
    }
}

/// Show or hide the desktop shell's "an AI assistant is in control" indicator.
///
/// `lingxia-control-runtime` drives this from its session events; a product
/// does not need to call it.
#[doc(hidden)]
pub fn set_control_session_indicator(active: bool) -> crate::Result<()> {
    crate::runtime::platform()?
        .set_control_session_indicator(active)
        .map_err(crate::Error::from)
}

/// What the indicator's Stop button does. Installed by the control runtime.
#[doc(hidden)]
pub fn set_control_session_stop_handler(handler: impl Fn() + Send + Sync + 'static) {
    lingxia_platform::set_control_session_stop_handler(std::sync::Arc::new(handler));
}

/// Requests host app termination through the active platform runtime.
pub fn exit() -> crate::Result<()> {
    crate::bootstrap::teardown_runner_display_language_session();
    crate::runtime::platform()?
        .exit()
        .map_err(crate::Error::from)?;
    Ok(())
}

fn state_file_in(root: impl AsRef<Path>, name: &str) -> crate::Result<PathBuf> {
    validate_state_file_name(name)?;
    Ok(lingxia_app_context::app_state_file(root.as_ref(), name))
}

fn validate_state_file_name(name: &str) -> crate::Result<()> {
    let path = Path::new(name);
    if name.trim().is_empty() {
        return Err(crate::Error::invalid_request("state file name is empty"));
    }
    if path
        .components()
        .any(|component| !matches!(component, Component::Normal(_) | Component::CurDir))
    {
        return Err(crate::Error::invalid_request(
            "state file name must be relative and stay inside the state directory",
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, mpsc};
    use std::time::{Duration, Instant};

    #[test]
    fn display_language_watchers_follow_the_service() {
        let (sender, events) = mpsc::channel();
        let sender = Mutex::new(sender);
        let subscription = watch_display_language(move |tag| {
            let _ = sender.lock().unwrap().send(tag);
        });
        let mut changes = display_language_changes();
        events.recv_timeout(Duration::from_secs(2)).unwrap();
        // The stream starts from the current value too, with no waiting.
        assert!(matches!(
            futures_core::Stream::poll_next(
                std::pin::Pin::new(&mut changes),
                &mut std::task::Context::from_waker(std::task::Waker::noop())
            ),
            std::task::Poll::Ready(Some(_))
        ));

        let wanted = LanguageTag::parse("fr-FR").unwrap();
        let owner = lxapp::install_display_language_session_override(
            DisplayLanguagePreference::LanguageTag(wanted.clone()),
        );
        // Other tests move the shared service too; every change still arrives.
        let deadline = Instant::now() + Duration::from_secs(2);
        while events.recv_timeout(deadline - Instant::now()).unwrap() != wanted {}
        lxapp::clear_display_language_session_override(owner);
        drop(subscription);
    }
}
