import * as fs from "fs";
import * as path from "path";
import type { PageTypeInfo, TypeInfo, MethodInfo } from "./builders/page-types.js";

export class TypeGenerator {
  private projectPath: string;

  constructor(projectPath: string) {
    this.projectPath = projectPath;
  }

  generatePageTypes(pagePath: string, typeInfo: PageTypeInfo): string {
    const dataFields = this.renderDataInterface(typeInfo.data);
    const actionMethods = this.renderActionsInterface(typeInfo.methods);

    return `// Auto-generated by lingxia-cli. DO NOT EDIT.
// Source: ${pagePath}

export interface PageData {
${dataFields}
}

export interface PageActions {
${actionMethods}
}

declare global {
  function useLingXia(): { data: PageData } & PageActions;
}

export {};
`;
  }

  private renderDataInterface(data: Record<string, TypeInfo>, indent = "  "): string {
    const entries = Object.entries(data);
    if (entries.length === 0) return `${indent}[key: string]: unknown;`;

    return entries
      .map(([key, info]) => {
        const optional = info.optional ? "?" : "";
        const typeStr = this.typeInfoToString(info);
        return `${indent}${this.escapePropertyName(key)}${optional}: ${typeStr};`;
      })
      .join("\n");
  }

  private renderActionsInterface(methods: Record<string, MethodInfo>, indent = "  "): string {
    const entries = Object.entries(methods);
    if (entries.length === 0) return `${indent}[key: string]: (...args: unknown[]) => void;`;

    return entries
      .map(([name, info]) => {
        const params = this.renderMethodParams(info.params);
        const returnType = info.returnType || "void";
        return `${indent}${this.escapePropertyName(name)}(${params}): ${returnType};`;
      })
      .join("\n");
  }

  private renderMethodParams(params: MethodInfo["params"]): string {
    if (params.length === 0) return "";

    return params
      .map((p) => {
        const optional = p.optional ? "?" : "";
        return `${p.name}${optional}: ${p.type}`;
      })
      .join(", ");
  }

  private typeInfoToString(info: TypeInfo): string {
    switch (info.type) {
      case "string":
      case "number":
      case "boolean":
      case "null":
      case "unknown":
        return info.type;

      case "array":
        if (info.elementType) {
          const elementType = this.typeInfoToString(info.elementType);
          // Wrap complex types in parentheses for array notation
          if (elementType.includes("|") || elementType.includes("&")) {
            return `(${elementType})[]`;
          }
          return `${elementType}[]`;
        }
        return "unknown[]";

      case "object":
        if (info.properties && Object.keys(info.properties).length > 0) {
          const props = Object.entries(info.properties)
            .map(([key, propInfo]) => {
              const optional = propInfo.optional ? "?" : "";
              return `${this.escapePropertyName(key)}${optional}: ${this.typeInfoToString(propInfo)}`;
            })
            .join("; ");
          return `{ ${props} }`;
        }
        return "Record<string, unknown>";

      default:
        return "unknown";
    }
  }

  private escapePropertyName(name: string): string {
    // If name contains special characters or starts with a number, quote it
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
      return name;
    }
    return `"${name.replace(/"/g, '\\"')}"`;
  }

  writeTypesForPage(pagePath: string, content: string): void {
    // Convert page path to types path
    // e.g., "pages/home/index.tsx" -> ".lingxia/types/pages/home/index.d.ts"
    const relativePath = pagePath.replace(/\.(tsx?|vue)$/, ".d.ts");
    const typesDir = path.join(this.projectPath, ".lingxia", "types");
    const outputPath = path.join(typesDir, relativePath);

    // Ensure directory exists
    const outputDir = path.dirname(outputPath);
    fs.mkdirSync(outputDir, { recursive: true });

    // Write the types file
    fs.writeFileSync(outputPath, content, "utf-8");
  }

  writeTypesConfig(): void {
    const typesDir = path.join(this.projectPath, ".lingxia", "types");
    fs.mkdirSync(typesDir, { recursive: true });

    // Write a tsconfig.json for the types directory
    const tsconfigPath = path.join(typesDir, "tsconfig.json");
    const tsconfig = {
      compilerOptions: {
        target: "ESNext",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        skipLibCheck: true,
        declaration: true,
        declarationMap: false,
        emitDeclarationOnly: true,
        noEmit: false,
      },
      include: ["**/*.d.ts"],
    };

    fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2), "utf-8");

    // Write an index.d.ts that re-exports all page types
    // This will be updated as pages are built
  }

  generateIndexFile(pageTypePaths: string[]): void {
    const typesDir = path.join(this.projectPath, ".lingxia", "types");
    const indexPath = path.join(typesDir, "index.d.ts");

    const exports = pageTypePaths
      .map((p) => {
        // Convert "pages/home/index.d.ts" to "./pages/home/index"
        const importPath = "./" + p.replace(/\.d\.ts$/, "");
        // Create a namespace-friendly export name
        const exportName = p
          .replace(/\.d\.ts$/, "")
          .replace(/\//g, "_")
          .replace(/[^a-zA-Z0-9_]/g, "_");
        return `export * as ${exportName} from "${importPath}";`;
      })
      .join("\n");

    const content = `// Auto-generated by lingxia-cli. DO NOT EDIT.
${exports}
`;

    fs.writeFileSync(indexPath, content, "utf-8");
  }

  addToGitignore(): void {
    const gitignorePath = path.join(this.projectPath, ".gitignore");
    const entry = "\n# LingXia generated types\n.lingxia/\n";

    if (fs.existsSync(gitignorePath)) {
      const content = fs.readFileSync(gitignorePath, "utf-8");
      if (!content.includes(".lingxia/")) {
        fs.appendFileSync(gitignorePath, entry);
      }
    }
  }
}

export function createTypeGenerator(projectPath: string): TypeGenerator {
  return new TypeGenerator(projectPath);
}
