// Host Rust library. Exposes one route to the View via #[lingxia::native].
//
// The macro generates a sibling fn `<name>_host()` that returns the
// host-entry registration value — you do NOT write that fn yourself, and
// you cannot rename it.

use std::sync::Arc;

#[derive(serde::Deserialize)]
struct HelloInput {
    name: String,
}

#[derive(serde::Serialize)]
struct HelloOutput {
    greeting: String,
}

// Parameter ordering — enforced by the macro:
//   1. `Arc<lingxia::LxApp>`         (optional, must be FIRST when present)
//   2. JSON payload (any serde::Deserialize type)  (optional)
//   3. `lingxia::host::HostCancel`   (optional, must be LAST when present)
//
// Return type must be `lingxia::Result<T>` where T: serde::Serialize.
#[lingxia::native("greet.hello")]
async fn greet_hello(
    _app: Arc<lingxia::LxApp>,
    input: HelloInput,
) -> lingxia::Result<HelloOutput> {
    Ok(HelloOutput {
        greeting: format!("Hello, {}!", input.name),
    })
}

struct AppHostAddon;

impl lingxia::HostAddon for AppHostAddon {
    fn install_host_apis(&self) {
        // greet_hello_host() is generated by the #[lingxia::native] macro
        // applied to `greet_hello` above. Register one per route.
        lingxia::host::register_host_entry(greet_hello_host());
    }

    fn start_services(&self) {
        // Background services go here (devtool bridge, push, ipc, …).
        // None in this example.
    }
}

// Platform FFI export. Apple platforms call this symbol from the SDK at
// startup. Android uses a `Java_<package>_<class>_nativeRegisterHostAddon`
// JNI entrypoint; Harmony uses a `#[napi]`-annotated function. See the
// skill's native/development.md for the full set.
#[cfg(any(target_os = "ios", target_os = "macos"))]
#[unsafe(no_mangle)]
pub extern "C" fn lingxia_register_host_addon() {
    lingxia::register_host_addon(Box::new(AppHostAddon));
}
