export { spec, expect, rawAutomation } from "./runtime.js";
export { AssertionError } from "./expect.js";
export { TimeoutError } from "./fixture.js";
export { TEST_ERROR_CODES } from "./errors.js";
export type {
  ActionOptions,
  AnyLogicPage,
  ArgOptions,
  EvalOptions,
  Expect,
  ExpectOptions,
  ExpectResult,
  FailOptions,
  FileOptions,
  Fixture,
  FunctionMatchers,
  InputOptions,
  JsonValue,
  Jsonable,
  Locator,
  LocatorFilterOptions,
  LocatorMatchers,
  LocatorOptions,
  LocatorState,
  LocatorWaitOptions,
  LogicApp,
  LogicCallOptions,
  LogicDataOptions,
  LogicFunction,
  LogicMethodResult,
  LogicPage,
  LogicPageMethod,
  LogicScope,
  Matchers,
  NavBackOptions,
  NavOptions,
  NavWaitOptions,
  NeedsMatcher,
  NetworkCall,
  OpenApiRun,
  ProfileCheckpoint,
  ProfileFixture,
  ProfileRestoreOptions,
  PromiseNotAllowed,
  RejectExpected,
  RestoreProfileOptions,
  RetryMatchers,
  ScenarioCallTarget,
  SpecBody,
  SpecOptions,
  SpecRequirements,
  TestApp,
  TestAutomation,
  TestClock,
  TestErrorCode,
  TestLogic,
  TestMock,
  TestNav,
  TestNetwork,
  TestRoute,
  TestScenario,
  TestView,
  ViewDocument,
  ViewElement,
  ViewEvalOptions,
  ViewFunction,
  ViewScope,
  ViewWindow,
  WaitForCallOptions,
  WaitForOptions,
} from "./types.js";
export type { AutomationErrorCode, ClockAdvance, ClockState } from "@lingxia/types/automation";
