export { spec, expect, run, reset, trackPublicSurface } from "./runtime.js";
export { AssertionError, logAssertion, setAssertionSink } from "./expect.js";
export { TimeoutError } from "./fixture.js";
export { renderJUnit } from "./junit.js";
export { PUBLIC_CAPABILITIES } from "./inventory.js";
export type { Capability, CapabilityLayer } from "./inventory.js";
export {
  VERSION,
  PACKAGE_NAME,
  DEFAULT_ACTION_TIMEOUT_MS,
  DEFAULT_SPEC_TIMEOUT_MS,
} from "./version.js";
export type {
  ActionOptions,
  Apps,
  ArgOptions,
  AssertionRecord,
  AttachmentRef,
  CaseRecord,
  ExpectOptions,
  FailOptions,
  FailurePage,
  FailureRecord,
  Fixture,
  FixtureExpect,
  JsonReport,
  JsonValue,
  LogicApp,
  LogicFunction,
  LogicPage,
  LogicScope,
  PageDataOptions,
  PageFunction,
  PageScope,
  ProfileFixture,
  ProfileRestoreOptions,
  RestoreProfileOptions,
  RunMeta,
  LingxiaTestController,
  Locator,
  LocatorFilterOptions,
  LocatorMatchers,
  LocatorOptions,
  LocatorState,
  LocatorWaitOptions,
  Matchers,
  NetworkCall,
  ProtocolReport,
  RejectExpected,
  RetryMatchers,
  SpecBody,
  SpecOptions,
  SpecStatus,
  StepRecord,
  TestApp,
  TestAutomation,
  TestPage,
  WaitForOptions,
} from "./types.js";
export type { AutomationErrorCode } from "@lingxia/types/automation";
