//! Native library for the example app (builds to .so/.a).
//!
//! This crate:
//! 1. Re-exports platform FFI symbols from lingxia
//! 2. Exports host addon registration via platform FFI (JNI/NAPI/C)

// Re-export platform FFI symbols from lingxia
#[cfg(target_os = "android")]
pub use lingxia::android::*;

{{APPLE_REEXPORT}}
{{HARMONY_REEXPORT}}

// Auto-generated by build.rs; defines `__lingxia_native::install()`.
include!(concat!(env!("OUT_DIR"), "/lingxia_native_handlers.rs"));

struct AppHostAddon;

impl lingxia::HostAddon for AppHostAddon {
    fn install_host_apis(&self) {
        __lingxia_native::install();
    }

    fn start_services(&self) {
        #[cfg(all(feature = "devtools", any(target_os = "ios", target_os = "macos")))]
        lingxia_control_runtime::start_dev_session_bridge_from_env();
        #[cfg(feature = "control")]
        if let Err(error) = lingxia_control_runtime::local_control::install() {
            log::warn!("control socket unavailable: {error}");
        }
    }
}

fn register_host_addons() {
    static REGISTER: std::sync::Once = std::sync::Once::new();
    REGISTER.call_once(|| lingxia::register_host_addon(Box::new(AppHostAddon)));
}

/// Answer as this product's command line if that is what this invocation is,
/// and return the exit code. `None` means carry on and be the app.
///
/// The Windows executable calls this as the first thing in `main`.
#[cfg(all(feature = "control", target_os = "windows"))]
pub fn run_cli_if_invoked() -> Option<i32> {
    register_host_addons();
    lingxia::product_cli::run_if_invoked()
}

{{ANDROID_EXPORT_BLOCK}}
{{HARMONY_EXPORT_BLOCK}}
{{APPLE_EXPORT_BLOCK}}
{{WINDOWS_EXPORT_BLOCK}}
