//! One dispatcher for every navigation entry point.
//!
//! Notification taps, menus, the tray, and inbound App Links all resolve to a
//! [`NavigationTarget`] and land here, so cold and warm start take the same
//! path with the same target.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

use serde_json::Value;

use super::registry;
use super::target::{NavigationError, NavigationTarget};

/// Queued activations that arrived before the host was ready. Bounded, so a
/// host that never becomes ready drops taps instead of growing without limit.
const MAX_PENDING: usize = 8;
const PENDING_DEADLINE: Duration = Duration::from_secs(45);

/// Which product entry point produced a request. Generated by the framework,
/// never taken from a payload, and used for behavior and diagnostics only —
/// it grants nothing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NavigationSource {
    Notification,
    AppLink,
    Menu,
    Tray,
    Devtool,
}

impl NavigationSource {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Notification => "notification",
            Self::AppLink => "appLink",
            Self::Menu => "menu",
            Self::Tray => "tray",
            Self::Devtool => "devtool",
        }
    }
}

#[derive(Debug, Clone)]
pub struct NavigationRequest {
    pub target: NavigationTarget,
    pub source: NavigationSource,
    /// The public notification id, when a notification tap produced this.
    pub notification_id: Option<String>,
}

impl NavigationRequest {
    pub fn new(target: NavigationTarget, source: NavigationSource) -> Self {
        Self {
            target,
            source,
            notification_id: None,
        }
    }

    pub fn from_notification(target: NavigationTarget, id: impl Into<String>) -> Self {
        Self {
            target,
            source: NavigationSource::Notification,
            notification_id: Some(id.into()),
        }
    }

    /// Schema-checked route parameter. `None` for any other target kind.
    pub fn param(&self, name: &str) -> Option<&Value> {
        match &self.target {
            NavigationTarget::Route { params, .. } => params.get(name),
            _ => None,
        }
    }

    pub fn param_str(&self, name: &str) -> Option<&str> {
        self.param(name).and_then(Value::as_str)
    }

    pub fn route_name(&self) -> Option<&str> {
        match &self.target {
            NavigationTarget::Route { name, .. } => Some(name),
            _ => None,
        }
    }
}

type ActivateHandler = Arc<dyn Fn() + Send + Sync>;
type FeedbackHandler = Arc<dyn Fn(&NavigationError) + Send + Sync>;

static ACTIVATE: OnceLock<ActivateHandler> = OnceLock::new();
static FEEDBACK: OnceLock<FeedbackHandler> = OnceLock::new();
static READY: AtomicBool = AtomicBool::new(false);
static NEXT_PENDING: AtomicU64 = AtomicU64::new(0);

fn pending() -> &'static Mutex<Vec<(u64, Instant, NavigationRequest)>> {
    static PENDING: OnceLock<Mutex<Vec<(u64, Instant, NavigationRequest)>>> = OnceLock::new();
    PENDING.get_or_init(|| Mutex::new(Vec::new()))
}

/// Bring the product forward. Installed by the host bootstrap.
pub fn install_activate_handler(handler: impl Fn() + Send + Sync + 'static) {
    let _ = ACTIVATE.set(Arc::new(handler));
}

/// Tell the user a target cannot be opened. Installed by the host bootstrap;
/// without one the reason is only logged.
pub fn install_feedback_handler(handler: impl Fn(&NavigationError) + Send + Sync + 'static) {
    let _ = FEEDBACK.set(Arc::new(handler));
}

/// Bring the product forward without navigating anywhere.
pub fn activate() {
    if let Some(handler) = ACTIVATE.get() {
        handler();
    }
}

pub fn report_unavailable(error: &NavigationError) {
    log::warn!("navigation target unavailable: {error}");
    if let Some(handler) = FEEDBACK.get() {
        handler(error);
    }
}

/// Route registration is sealed and the runtime can open targets. Drains
/// whatever arrived during startup.
pub fn mark_ready() {
    if READY.swap(true, Ordering::SeqCst) {
        return;
    }
    let queued = {
        let mut queue = pending().lock().unwrap_or_else(|error| error.into_inner());
        std::mem::take(&mut *queue)
    };
    for (_, queued_at, request) in queued {
        if queued_at.elapsed() > PENDING_DEADLINE {
            log::warn!(
                "dropping {} activation for {}: the host was not ready in time",
                request.source.as_str(),
                request.target.describe()
            );
            continue;
        }
        deliver(&request);
    }
}

pub fn is_ready() -> bool {
    READY.load(Ordering::SeqCst)
}

/// Validate and open, or queue until the host is ready.
///
/// Validation runs here as well as at publish time: a route can be removed, or
/// an App Link host allowlist tightened, between the two.
pub fn dispatch(request: NavigationRequest) -> Result<(), NavigationError> {
    validate(&request.target)?;
    if !is_ready() {
        return enqueue(request);
    }
    deliver(&request);
    Ok(())
}

/// Publish-time check. The same rules the dispatcher applies on a tap.
pub fn validate(target: &NavigationTarget) -> Result<(), NavigationError> {
    target.check_shape()?;
    match target {
        NavigationTarget::Activate => Ok(()),
        NavigationTarget::Route { name, params } => registry::validate(name, params),
        NavigationTarget::AppLink { url } => match crate::applink::parse(url) {
            Ok(Some(_)) => Ok(()),
            Ok(None) | Err(_) => Err(NavigationError::invalid(
                "target.url must be an https URL on a configured App Link host",
            )),
        },
    }
}

fn enqueue(request: NavigationRequest) -> Result<(), NavigationError> {
    let sequence = NEXT_PENDING.fetch_add(1, Ordering::Relaxed);
    {
        let mut queue = pending().lock().unwrap_or_else(|error| error.into_inner());
        if queue.len() >= MAX_PENDING {
            return Err(NavigationError::unavailable(
                "too many activations are already waiting for the host to start",
            ));
        }
        queue.push((sequence, Instant::now(), request));
    }
    // Re-checked per entry rather than once globally: a host that never
    // becomes ready must still release each waiter at its own deadline.
    std::thread::spawn(move || {
        std::thread::sleep(PENDING_DEADLINE);
        expire(sequence);
    });
    Ok(())
}

fn expire(sequence: u64) {
    let dropped = {
        let mut queue = pending().lock().unwrap_or_else(|error| error.into_inner());
        queue
            .iter()
            .position(|(queued, _, _)| *queued == sequence)
            .map(|index| queue.remove(index))
    };
    if let Some((_, _, request)) = dropped {
        let error = NavigationError::unavailable("the product did not finish starting in time");
        log::warn!(
            "dropping {} activation for {}: {error}",
            request.source.as_str(),
            request.target.describe()
        );
        report_unavailable(&error);
    }
}

fn deliver(request: &NavigationRequest) {
    let outcome = match &request.target {
        NavigationTarget::Activate => {
            activate();
            Ok(())
        }
        NavigationTarget::Route { name, .. } => registry::open(request, name),
        NavigationTarget::AppLink { url } => match crate::applink::deliver(url) {
            1 => Ok(()),
            0 => Err(NavigationError::unavailable(
                "this link is not on a configured App Link host",
            )),
            _ => Err(NavigationError::unavailable(
                "no App Link handler is installed",
            )),
        },
    };
    match outcome {
        Ok(()) => log::info!(
            "navigation from {} opened {}",
            request.source.as_str(),
            request.target.describe()
        ),
        Err(error) => report_unavailable(&error),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn requests_expose_only_schema_checked_params() {
        let request = NavigationRequest::from_notification(
            NavigationTarget::Route {
                name: "orders.detail".into(),
                params: serde_json::json!({ "orderId": "42" })
                    .as_object()
                    .cloned()
                    .unwrap(),
            },
            "order:42",
        );
        assert_eq!(request.route_name(), Some("orders.detail"));
        assert_eq!(request.param_str("orderId"), Some("42"));
        assert_eq!(request.param_str("missing"), None);
        assert_eq!(request.source, NavigationSource::Notification);
    }

    #[test]
    fn activate_requests_carry_no_params() {
        let request = NavigationRequest::new(NavigationTarget::Activate, NavigationSource::Tray);
        assert_eq!(request.route_name(), None);
        assert_eq!(request.param("anything"), None);
    }
}
