use ::lxapp::lx::{LxLogicExtension, register_logic_extension};
use rong::{JSContext, JSResult};

mod app;
mod device;
mod display;
mod env;
mod fs;
pub mod i18n;
mod input;
mod location;
mod lxapp;
mod media;
mod message_port;
mod navigator;
mod public_types;
mod share;
mod storage;
mod surface;
mod system;
mod task_object;
mod ui;
mod update;

// Auto-generated by `cargo run -p lingxia-cli -- gen i18n ...`.
mod i18n_generated;
pub use self::i18n_generated::*;

pub struct LxLogicRuntime;

impl LxLogicExtension for LxLogicRuntime {
    fn init(&self, ctx: &JSContext) -> JSResult<()> {
        public_types::init(ctx)?;
        env::init(ctx)?;
        app::init(ctx)?;
        lxapp::init(ctx)?;
        device::init(ctx)?;
        display::init(ctx)?;
        location::init(ctx)?;
        navigator::init(ctx)?;
        update::init(ctx)?;
        message_port::init(ctx)?;
        surface::init(ctx)?;
        input::init(ctx)?;
        ui::init(ctx)?;
        system::init(ctx)?;
        share::init(ctx)?;
        media::init(ctx)?;
        fs::init(ctx)?;
        storage::init(ctx)?;
        Ok(())
    }
}

pub fn register_logic_runtime() {
    ::lxapp::register_surface_close_observer(notify_surface_closed);
    ::lxapp::register_surface_context_observer(surface::notify_surface_context_changed);
    register_logic_extension(Box::new(LxLogicRuntime));
    register_platform_dialog_i18n();
}

/// Installs the locale-aware translator the platform layer uses for native
/// dialog titles (file/media choosers). `lingxia-platform` can't reach the
/// i18n table directly (it sits below it), so the logic layer maps its keys
/// to [`I18nKey`] here.
fn register_platform_dialog_i18n() {
    lingxia_platform::i18n::set_dialog_translator(|key| {
        let i18n_key = match key {
            "common.about" => I18nKey::CommonAbout,
            "common.exit" => I18nKey::CommonExit,
            "common.version" => I18nKey::CommonVersion,
            "file_chooser.select_folder" => I18nKey::FileChooserSelectFolder,
            "file_chooser.select_file" => I18nKey::FileChooserSelectFile,
            "file_chooser.choose_images" => I18nKey::FileChooserChooseImages,
            "file_chooser.choose_videos" => I18nKey::FileChooserChooseVideos,
            "file_chooser.choose_media" => I18nKey::FileChooserChooseMedia,
            _ => return None,
        };
        Some(i18n::t(i18n_key))
    });
}

pub fn notify_surface_closed(id: &str, reason: &str) -> bool {
    surface::notify_surface_closed(id, reason)
}
