//! `.lingxia/types/pages.d.ts` — the project's configured page names as types.
//!
//! `@lingxia/types` ships an empty `LxAppPages`, so `ConfiguredPageName` is
//! plain `string` until this file exists. Writing it merges the project's own
//! names in, and every navigation call narrows to them.

use crate::lxapp::project::Project;
use anyhow::{Context, Result};
use std::fs;

const HEADER: &str = "// Generated by the lingxia CLI from this project's manifest. Do not edit.\n\
                      // Regenerated on every build; `.lingxia/` is not checked in.\n";

pub fn generate(project: &Project) -> Result<()> {
    let dir = project.root.join(".lingxia").join("types");
    fs::create_dir_all(&dir)
        .with_context(|| format!("create page types directory {}", dir.display()))?;
    let path = dir.join("pages.d.ts");
    let next = render(&project.page_names);
    // Rewriting an identical file would churn the watcher for no reason.
    if fs::read_to_string(&path).is_ok_and(|current| current == next) {
        return Ok(());
    }
    fs::write(&path, next).with_context(|| format!("write {}", path.display()))
}

fn render(page_names: &[String]) -> String {
    let mut out = String::from(HEADER);
    out.push_str("\ninterface LxAppPages {\n");
    for name in page_names {
        // A name that is not a bare identifier still has to be a valid key.
        out.push_str(&format!("  {}: true;\n", quote_key(name)));
    }
    out.push_str("}\n");
    out
}

fn quote_key(name: &str) -> String {
    let bare = !name.is_empty()
        && !name.starts_with(|c: char| c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if bare {
        name.to_string()
    } else {
        format!("{name:?}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_bare_and_quoted_keys() {
        let rendered = render(&["home".into(), "my-page".into(), "2fa".into()]);
        assert!(rendered.contains("  home: true;\n"));
        assert!(rendered.contains("  \"my-page\": true;\n"));
        assert!(rendered.contains("  \"2fa\": true;\n"));
    }

    #[test]
    fn an_lxapp_without_pages_still_declares_the_interface() {
        let rendered = render(&[]);
        assert!(rendered.contains("interface LxAppPages {\n}\n"));
    }
}
