//! Cloud-worker dev support for an lxapp: transpile the worker's `.ts` mocks
//! to loadable `.js`, and generate typed `lx.cloud.invoke` declarations. Driven
//! by the lxapp's `worker.json` (`dir`).

use anyhow::Result;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// If the lxapp declares a cloud worker (`worker.json`), regenerate typed
/// `lx.cloud.invoke`, transpile the worker's `.ts` mocks to a `.js` dir the mock
/// backend can load, and return that dir. None when there are no cloud functions.
pub(crate) fn prepare_dev(lxapp_path: &Path) -> Option<PathBuf> {
    let worker = read_worker(lxapp_path)?;
    generate_types(lxapp_path, &worker);

    let mocks_dir = lxapp_path.join(&worker).join("mocks");
    if !mocks_dir.is_dir() {
        return None;
    }
    let load_dir = lxapp_path.join(".lingxia").join("cloud-mocks");
    let _ = std::fs::remove_dir_all(&load_dir);
    if let Err(err) = transpile_mock_tree(&mocks_dir, &load_dir) {
        eprintln!("[cloud] mock transpile failed: {err:#}");
        return None;
    }
    Some(load_dir)
}

/// The worker dir declared in `<lxapp>/worker.json` (`dir`, default `server`);
/// None when the lxapp has no `worker.json`.
fn read_worker(lxapp_path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(lxapp_path.join("worker.json")).ok()?;
    let config = serde_json::from_str::<serde_json::Value>(&text)
        .map_err(|_| eprintln!("[cloud] worker.json is not valid JSON"))
        .ok()?;
    Some(
        config
            .get("dir")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("server")
            .to_string(),
    )
}

/// Recursively transpile `.ts` mocks to `.js` (and copy `.js`) from `src` into
/// `out`, preserving structure so relative imports resolve in the mock bundler.
fn transpile_mock_tree(src: &Path, out: &Path) -> Result<()> {
    std::fs::create_dir_all(out)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            transpile_mock_tree(&path, &out.join(entry.file_name()))?;
        } else if path.extension().is_some_and(|ext| ext == "ts") {
            let source = std::fs::read_to_string(&path)?;
            let js = super::logic::transpile_module(&path, &source)?;
            std::fs::write(out.join(entry.file_name()).with_extension("js"), js)?;
        } else if path.extension().is_some_and(|ext| ext == "js") {
            std::fs::copy(&path, out.join(entry.file_name()))?;
        }
    }
    Ok(())
}

/// Generate `.lingxia/types/cloud-functions.d.ts` so `lx.cloud.invoke` is typed.
/// Each `src/functions/<file>.ts` exporting a `<Name>Input`/`<Name>Output` pair
/// contributes a function `<name>` whose I/O references that file via
/// `import(...)`. Self-augments `Lx` here, so `@lingxia/types` carries nothing
/// cloud-specific. Reads exported types only; never the worker's `lx.fn` code.
fn generate_types(lxapp_path: &Path, worker: &str) {
    let functions_dir = lxapp_path.join(worker).join("src").join("functions");
    let Ok(read) = std::fs::read_dir(&functions_dir) else {
        return;
    };
    let mut files: Vec<PathBuf> = read
        .flatten()
        .map(|entry| entry.path())
        .filter(|p| p.extension().is_some_and(|x| x == "ts"))
        .collect();
    files.sort();

    let worker_rel = worker.trim_start_matches("./");
    // (function name, InputType, OutputType, file stem the types live in)
    let mut entries: Vec<(String, String, String, String)> = Vec::new();
    for file in &files {
        let (Ok(src), Some(stem)) = (
            std::fs::read_to_string(file),
            file.file_stem().and_then(|s| s.to_str()),
        ) else {
            continue;
        };
        let exported = exported_type_names(&src);
        for name in &exported {
            if let Some(base) = name.strip_suffix("Input") {
                let output = format!("{base}Output");
                if exported.contains(&output) {
                    entries.push((lower_first(base), name.clone(), output, stem.to_string()));
                }
            }
        }
    }
    if entries.is_empty() {
        return;
    }
    entries.sort();

    let mut map = String::new();
    for (name, input, output, stem) in &entries {
        let rel = format!("../../{worker_rel}/src/functions/{stem}");
        map.push_str(&format!(
            "  {name}: {{\n    input: import(\"{rel}\").{input};\n    output: import(\"{rel}\").{output};\n  }};\n"
        ));
    }

    // The cloud surface (function map + `invoke`) is declared in THIS file, so
    // @lingxia/types stays cloud-free; only the `cloud` accessor is grafted onto
    // `Lx` (unavoidable — `lx` is typed `Lx`), referencing this file's `LxCloud`.
    let mut out = String::new();
    out.push_str("// Generated by `lingxia dev` — do not edit.\n");
    out.push_str("// The cloud-function surface lives here (provider side), not in\n");
    out.push_str("// @lingxia/types; only the `cloud` accessor is grafted onto `lx`.\n");
    out.push_str("import type {} from \"@lingxia/types\";\n\n");
    out.push_str("export interface LxCloudFunctions {\n");
    out.push_str(&map);
    out.push_str("}\n\n");
    out.push_str("export interface LxCloud {\n");
    out.push_str("  invoke<K extends string>(\n");
    out.push_str("    name: K,\n");
    out.push_str("    ...args: K extends keyof LxCloudFunctions\n");
    out.push_str("      ? [input: LxCloudFunctions[K][\"input\"]]\n");
    out.push_str("      : [input?: unknown]\n");
    out.push_str("  ): Promise<K extends keyof LxCloudFunctions ? LxCloudFunctions[K][\"output\"] : unknown>;\n");
    out.push_str("}\n\n");
    out.push_str("declare module \"@lingxia/types\" {\n");
    out.push_str("  interface Lx {\n");
    out.push_str("    cloud: import(\"./cloud-functions\").LxCloud;\n");
    out.push_str("  }\n}\n");

    let out_dir = lxapp_path.join(".lingxia").join("types");
    if std::fs::create_dir_all(&out_dir).is_ok() {
        let _ = std::fs::write(out_dir.join("cloud-functions.d.ts"), out);
    }
}

/// Names exported as `export interface X` / `export type X` from a TS source.
fn exported_type_names(src: &str) -> HashSet<String> {
    let mut names = HashSet::new();
    for line in src.lines() {
        let line = line.trim_start();
        for kw in ["export interface ", "export type "] {
            if let Some(rest) = line.strip_prefix(kw) {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    names.insert(name);
                }
            }
        }
    }
    names
}

/// Lower-case the first character (PascalCase → camelCase).
fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}
